// Statisch host-draaiboek per stop, afgeleid uit The_Arrivals_ACHTERGROND_V2.md.
// HOOFDINFO bovenaan, daarna het verhaal als korte bullets met de vragen op hun plek.
// `question`-beats verwijzen naar vraag-id's in de DB (group_id = stop-id).

export type PlaybookBeat = { kind: 'note'; text: string } | { kind: 'question'; id: string }

export interface StopPlaybook {
  hoofdinfo: string[]
  script: PlaybookBeat[]
}

const n = (text: string): PlaybookBeat => ({ kind: 'note', text })
const q = (id: string): PlaybookBeat => ({ kind: 'question', id })

export const STOP_PLAYBOOK: Record<string, StopPlaybook> = {
  s1: {
    hoofdinfo: [
      'Gepland project van de Queensboro Corporation (MacDougall) — niet organisch gegroeid.',
      '"Heights" = pure marketing: een plat weiland ("Trains Meadow") dat het prestige van Brooklyn Heights leende.',
      'Gebouwd voor White Anglo-Saxon Protestants; geweerd: Joden, zwarte Amerikanen, in de praktijk ook katholieken/Italianen/Grieken.',
      'De uitsluiting zat óók in het coöperatie-model: bewoners kozen zelf wie er introk.',
    ],
    script: [
      n('Tot ~1900: moerassig boerenland, ver van de stad.'),
      n('Twee dingen veranderden alles: de Queensboro Bridge (1909) + de metro (1917, de latere 7) — Manhattan op forensenafstand.'),
      n('MacDougalls Queensboro Corporation kocht "Trains Meadow" op en bouwde er een compleet merk omheen.'),
      n('"Jackson" van Jackson Avenue; "Heights" geleend van Brooklyn Heights — terwijl het terrein kurkdroog vlak is.'),
      q('s1-q1'),
      n('De innovatie: de "garden apartment" — gesloten blokken rond een verborgen binnentuin.'),
      n('Het onzichtbare wás het punt: privé, exclusief, groen achter de gevel.'),
      n('Agressief verkocht: een van de eerste radioreclames; "restricted community" als verkoopargument, niet als schaamte.'),
      q('s1-q2'),
      n('De zeef, niveau 1: restrictieve aktes (covenants) — verkoop/verhuur aan bepaalde groepen verboden.'),
      n('Niveau 2, duurzamer: het coöperatie-model — de buren beslisten zélf wie introk.'),
      n('Tijdgenoot vatte de sfeer samen als "geen katholieken, Joden of honden".'),
      n('Pas onafdwingbaar in 1948 (Shelley v. Kraemer); zwarte bewoners informeel geweerd tot ná de Fair Housing Act (1968).'),
      q('s1-q3'),
      n('Verteltip: de Olmsted-tuin is "men zegt dat" — vertel als anekdote.'),
      n('Houd het mechanisme vast: deze zeef komt elke stop terug, telkens vermomd.'),
    ],
  },
  s2: {
    hoofdinfo: [
      'Scrabble bedacht door Alfred Butts (werkloze architect), ontwikkeld in de kelder van deze kerk. (1938 = "Criss-Cross Words"; naam "Scrabble" pas 1948 via James Brunot.)',
      "In de jaren '40 doorbraken Joden én homoseksuele mannen de witte utopie.",
      'Lange LGBT-traditie; het Jewish Center op 77th huisvest nu óók Hindoe-, Pinkster- en Iftar-diensten.',
    ],
    script: [
      n('De Depressie deed wat idealen niet deden: exclusiviteit werd onbetaalbaar.'),
      n('Een verhuurder kiest tussen "leeg" en "een Joods gezin" — en kiest het gezin. De zeef begint te haperen.'),
      q('s2-q2'),
      n('Twee soorten "ongewenste" nieuwkomers tegelijk: Joodse New Yorkers...'),
      n('...én homoseksuele mannen uit Manhattan (anonimiteit + betaalbaarheid).'),
      n('Dat is de kiem van de latere grootste Latino-LGBTQ-cultuur van de stad (Stop 8).'),
      q('s2-q1'),
      n('Het Scrabble-verhaal: Alfred Butts, architect zonder werk door de Depressie.'),
      n('Hij telde de letterfrequentie van het Engels (o.a. op de voorpagina van de NYT) om de punten te bepalen.'),
      n('Daarom: de E goedkoop en talrijk, de Q en Z zeldzaam en duur.'),
      n('Eerst "Criss-Cross Words" (1938); pas in 1948 koopt James Brunot de rechten en doopt het "Scrabble".'),
      q('s2-q3'),
      n('Eén gebouw, alle werelden: hier preekt men nu in Engels, Spaans én Mandarijn.'),
      n('Verderop het Jewish Center op 77th: nu óók Hindoe-, Pinkster- en Iftar-diensten.'),
      n('De palimpsest in religieuze vorm — dezelfde stenen, nieuwe stemmen die de ruimte delen.'),
    ],
  },
  s3: {
    hoofdinfo: [
      "Colombianen = eerste grote Latino-golf (jaren '50), lang de meest zichtbare; \"Little Colombia\" / Chapinero.",
      'Vandaag zijn Ecuadorianen de grootste groep (~16%), dan Colombianen; grote Dominicaanse, Mexicaanse en Bangladeshi-gemeenschappen.',
      'Arepa = maïskoek. Terraza 7 (Freddy Castiblanco) = cultuur als verzet tegen gentrificatie.',
      "Donkere kant: cocaïne-jaren '80 op Roosevelt; journalist Manuel de Dios Unanue vermoord (1992).",
    ],
    script: [
      n('Dit was decennialang "Little Colombia" / Chapinero (rond 82nd–83rd & Roosevelt).'),
      q('s3-q1'),
      n('Waarom toen? La Violencia (1948–58) dreef honderdduizenden Colombianen het land uit.'),
      n('JH bood drie dingen: goedkope huur, de 7-metro ("the International Express") naar werk in Manhattan...'),
      n('...én ketenmigratie: de eersten haalden een neef, een buurvrouw, soms een heel dorp uit Tolima na.'),
      q('s3-q3'),
      n('Maar het verhaal moet schuiven: vandaag zijn Ecuadorianen de grootste groep.'),
      n('Daarnaast grote Dominicaanse, Mexicaanse en Bangladeshi-gemeenschappen.'),
      n('"Latino" is geen monoliet — de buurt dwingt nabuurschap, geen eenheid.'),
      q('s3-q2'),
      n('Eerlijk over de schaduw: Roosevelt had in de jaren \'80 een zware reputatie in de cocaïne-economie.'),
      n('Symbool: journalist Manuel de Dios Unanue, in 1992 vermoord nadat hij het Cali-kartel blootlegde — een aanslag op de persvrijheid.'),
      n('Hoopvol tegenbeeld: Terraza 7 van Freddy Castiblanco — cultureel platform tegen verdringing.'),
      n('(Terraza opent pas ~17:00 — wijs het van buiten aan.) Proef hier de arepa.'),
      q('s3-q4'),
    ],
  },
  s4: {
    hoofdinfo: [
      'Roosevelt Ave (onder de 7) = de informele economie: remittances (~$650 mld/jr, meer dan alle ontwikkelingshulp), valse documenten, zichtbaar sekswerk.',
      'Lorena Borjas: "moeder van de trans-Latinx-gemeenschap van Queens". Mexicaanse migrant (1981), zelf slachtoffer van mensenhandel.',
      'Decennialange outreach: condooms/spuiten, hiv-tests, borgsommen, opvang bij haar thuis.',
      '2017 gepardonneerd (campagne o.l.v. Danny Dromm); stierf maart 2020 als vroeg COVID-slachtoffer.',
    ],
    script: [
      n('Twee straten, twee werelden: 37th Ave is de nette "sidewalk ballet".'),
      n('Roosevelt is rauwer, donkerder, onder de geribbelde schaduw van de 7-trein.'),
      n('Hier draait de "informele stad" — wat de officiële stad liever niet ziet, maar die de buurt draaiend houdt.'),
      q('s4-q1'),
      n('Het verbluffendste cijfer van de dag staat hier op straat: ~$650 miljard per jaar aan remittances.'),
      n('Méér dan het totale ontwikkelingshulpbudget van alle rijke landen samen.'),
      n('Dat geld omzeilt regeringen en corruptie — rechtstreeks naar oma\'s medicijnen of een zus\' schoolgeld.'),
      n('De geldtransferwinkels langs Roosevelt zijn de fysieke infrastructuur ervan.'),
      n('Eén vrouw belichaamt deze laag: Lorena Borjas.'),
      n('Op precies deze stoep bouwde ze decennialang een zorgnetwerk voor de meest kwetsbaren.'),
      n('Transvrouwen, sekswerkers, ongedocumenteerden, mensen met hiv: condooms, schone spuiten, hiv-tests, borgsommen, opvang bij haar thuis.'),
      q('s4-q2'),
      n('Ze verbindt vier draden: queer geschiedenis, sekswerk, migratie en de pandemie.'),
      n('In 2017 gepardonneerd (campagne o.l.v. Danny Dromm); maart 2020 een van de eerste COVID-doden van de stad.'),
      n('Vertel de straat via haar — rechten en waardigheid, geen sensatie.'),
    ],
  },
  s5: {
    hoofdinfo: [
      'Immigration & Nationality Act 1965 (Hart-Celler) schrapte de raciale quota en opende migratie uit Azië.',
      'Eerste Indiase migranten vaak hooggeschoold (artsen/ingenieurs/academici).',
      'De tweede verdiepingen = kantoortjes om het systeem te navigeren (green cards, SAT-prep, notarios).',
      'Na 9/11: Special Registration, detenties, surveillance; taxichauffeurs als doelwit; ontstaan van DRUM.',
      'De Partition (1947) verklaart de aparte India/Pakistan/Bangladesh-gemeenschappen.',
    ],
    script: [
      n('De belangrijkste wet van de dag.'),
      n('1924–1965 gold de "national origins quota" — bijna totale blokkade van Aziaten en Zuid-/Oost-Europeanen.'),
      n('1965 Hart-Celler verving dat door beroepsvaardigheid + gezinshereniging (getekend door Johnson bij het Vrijheidsbeeld).'),
      q('s5-q1'),
      n('De wetgevers dachten dat het de demografie nauwelijks zou veranderen — een van de grootste misrekeningen ooit.'),
      n('Voorrang voor hooggeschoolden → de eerste Indiërs waren artsen, ingenieurs, academici.'),
      n('Mehta zelf kwam in 1977 als 14-jarige; zijn ouders kwamen het familie-diamantbedrijf uitbreiden.'),
      n('74th St werd "Little India": sari-winkels, goud (cultureel én financieel), mithai-winkels.'),
      n('Het mythische Sam & Raj: 110 én 220 volt, en geen btw als je Gujarati sprak. (Nu dicht — vertel als geschiedenis.)'),
      n('Kijk omhoog: de tweede verdiepingen zijn "rabbit warrens" vol kantoortjes — green cards, SAT-prep, belasting, notarios.'),
      q('s5-q2'),
      n('De ondergrond: 1947, de Partition — Brits-Indië gesplitst langs religie (≈1 mln doden, 10–15 mln ontheemd).'),
      n('In 1971 scheidde Bangladesh zich af — een natie jonger dan veel van haar migranten.'),
      n('Gevolg hier: nazaten van mensen die thuis aan dodelijke grenzen stonden, wonen als buren.'),
      q('s5-q4'),
      n('En de belonging-crisis: na 9/11 werd dezelfde gemeenschap plots verdacht gemaakt.'),
      n('NSEERS/Special Registration: mannen 16+ uit moslimlanden moesten zich melden — verhoor, detentie, deportatie, uiteengevallen gezinnen.'),
      n('Hate crimes stegen; Zuid-Aziatische taxichauffeurs waren een bijzonder kwetsbaar doelwit.'),
      n('Hieruit ontstond hier DRUM (Desis Rising Up & Moving). De zeef in zijn modernste, lelijkste vorm.'),
      q('s5-q3'),
    ],
  },
  s6: {
    hoofdinfo: [
      'Nieuwste laag: Tibet, Nepal, Bhutan, Bangladesh. "Little Nepal" is minstens zo groot als de Tibetaanse aanwezigheid.',
      'Veel Tibetanen zijn vluchtelingen/ballingen; de Immigration Act van 1990 wees 1.000 visa toe aan ontheemde Tibetanen.',
      'Het food court was bioscoop Earle → Eagle (één letter — "het verhaal gaat dat").',
      'Diversity Plaza is sinds 2012 autovrij — het de-facto stadsplein.',
    ],
    script: [
      n('Migratie door verlies, niet door kansen.'),
      n('Na de Chinese annexatie van Tibet (1950) en de vlucht van de Dalai Lama (1959): een wereldwijde diaspora.'),
      n('De Immigration Act van 1990 wees 1.000 visa toe aan ontheemde Tibetanen; velen kwamen via India/Nepal uiteindelijk hier.'),
      q('s6-q2'),
      n('Zeg niet alleen "Tibetaans": de Nepalese gemeenschap is minstens zo groot — een echte "Little Nepal".'),
      n('Plus Bhutanezen en, verderop, een grote Bengaalse gemeenschap (apotheken, fuchka-karren, moskeeën).'),
      n('Het bindende gerecht is de momo (de dumpling) — er is zelfs een jaarlijkse Momo Crawl.'),
      q('s6-q1'),
      n('Het gebouw met vier levens — je beste palimpsest in één object:'),
      n('Art-deco-filmpaleis The Earle (jaren \'30) → pornofilms (\'70) → Bollywood-bioscoop (\'80) → Zuid-Aziatisch food court.'),
      n('Bij de Bollywood-stap veranderde — zo gaat het verhaal — één letter: Earle werd Eagle. Eén gevel, vier economieën.'),
      q('s6-q3'),
      n('Eet-moment: Kabab King op de hoek staat in de NYT-100 van 2026 — en in Mamdani\'s top 3.'),
      q('s6-q4'),
      n('De plaza zelf is sinds 2012 autovrij: schaaktafels, eetkraampjes, een dozijn talen.'),
      n('Een vroege voorbode van de autovrije Open Street waar we eindigen.'),
    ],
  },
  s7: {
    hoofdinfo: [
      "María Piedad Cano (de Arepa Lady) begon eind jaren '80 op een straatkar; nu een restaurant — informele economie die institutionaliseert.",
      'De nieuwe zeef = gentrificatie: documentatie/kredietchecks (die ook legale migranten missen) + prijs (300k → ~1 mln).',
      'Gevolg: kelderwoningen, soms "hot beds" (bedden in shifts).',
    ],
    script: [
      n("Het optimistische verhaal: María Piedad Cano bakte jarenlang 's nachts arepa's op een kar op Roosevelt."),
      n('Cultstatus onder foodies → een echt restaurant (gerund door haar zonen). Informeel → reputatie → formeel.'),
      q('s7-q1'),
      n('Proef de arepa de choclo — zoete jonge maïs onder een deken van gesmolten kaas.'),
      q('s7-q3'),
      n('De keerzijde is je rode draad: gentrificatie. Garden apartments van ~300k naderen het miljoen.'),
      n('Het venijn zit niet alleen in de huur maar in documentatie — krediet, referenties, papieren.'),
      n('Die mist een recent gearriveerde (ook legale) migrant. Gevolg: een schaduwmarkt van kelderwoningen, soms "hot beds" (bedden in shifts).'),
      q('s7-q2'),
      n('Maak de cirkel met Stop 1 hardop: in 1910 sloot een coöperatie-stemming mensen buiten.'),
      n('In 2026 doet een kredietscore hetzelfde werk. Dezelfde machine, ander pak.'),
    ],
  },
  s8: {
    hoofdinfo: [
      'In 1990 werd Julio Rivera (29, homoseksuele barman) door skinheads vermoord — een beruchte hate crime.',
      'Eruit ontstond de Queens Pride Parade, opgericht door buurtbewoner/leraar Danny Dromm (later raadslid).',
      'Queer lijn: Rivera (1990) → Lorena Borjas (2020), dertig jaar op dezelfde straten.',
    ],
    script: [
      n("Het dieptepunt: late jaren '80/vroege '90 — criminaliteit, stedelijk verval, de aidsepidemie."),
      n('In 1990 werd Julio Rivera (29, homoseksuele barman) naar een schoolplein gelokt en door skinheads vermoord, enkel omdat hij homo was.'),
      n('Een van de eerste zaken in NY die als anti-homo hate crime werd vervolgd. Deze hoek draagt nu zijn naam.'),
      q('s8-q1'),
      n('Wat eruit groeide: de Queens Pride Parade (eerste editie 1993), mede opgericht door leraar Danny Dromm.'),
      n('Dezelfde Dromm die later het pardon van Lorena Borjas (Stop 4) bevocht — één queer lijn, dertig jaar.'),
      n('Vandaag: de op één na grootste Pride van de stad, in een buurt met óók zeer conservatieve gemeenschappen.'),
      q('s8-q2'),
      n('Het eerlijke punt (Mehta): geen plotselinge liefde, maar "het zakken van de wapens".'),
      n('Een buurt die iemand vermoordde om wie hij was, viert hem nu. Verandering die bevochten is.'),
    ],
  },
  s9: {
    hoofdinfo: [
      'Jackson Heights was voorjaar 2020 het epicentrum van de COVID-uitbraak in NYC.',
      'Uit de crisis groeide de 34th Avenue Open Street (±2 mijl autovrij) — "de eerste superblock van New York".',
      'Van afgeschermde privételuin (1910) naar heroverde publieke straat (2020): het hele verhaal in één gebaar.',
      'Dit is het slot — sluit af met de slotvraag en laat de groep het laatste woord.',
    ],
    script: [
      n('Waarom hier zo hard: twee dingen tegelijk.'),
      n('Dichtheid: de gedeelde kelderwoningen maakten isoleren vrijwel onmogelijk.'),
      n('Beroep: de bewoners waren essentiële werkers (taxi, bezorging, schoonmaak, zorg) die niet konden thuiswerken.'),
      n('Elmhurst Hospital werd het nationale symbool; koelwagens als mortuaria. Borjas stierf in deze weken.'),
      q('s9-q2'),
      n('En precies hier vocht de gemeenschap iets hoopvols af: de 34th Ave Open Street.'),
      n('Twee mijl dagelijks autovrij — kinderen leren fietsen, senioren met klapstoelen, spontane Zumba en yoga op het asfalt.'),
      n('Wordt nu geprezen als model en beschreven als "de eerste superblock van New York".'),
      q('s9-q1'),
      n('De cirkel sluit — het mooiste geografische gebaar van de tour:'),
      n('1910 ontworpen rond verborgen privétuinen — groen als exclusief bezit.'),
      n('100 jaar later de straat zélf heroverd als gedeelde publieke ruimte. Privé → publiek: het hele verhaal in één beweging.'),
      n('Sluit af zonder moraal — laat de groep praten:'),
      q('s9-q3'),
    ],
  },
  s10: {
    hoofdinfo: [
      'Optioneel — de tour sluit inhoudelijk af bij Stop 9; Jahn\'s is een bonus met ijs.',
      'Jahn\'s: de keten begon 1897 (Bronx); deze vestiging draait sinds 1959 en is de laatste die nog open is (gerenoveerd 2025).',
      'Handelsmerk: de Kitchen Sink Sundae for eight — alleen samen op te eten.',
    ],
    script: [
      n('De gemeenschappelijke noemer onder alle lagen van de buurt.'),
      n('Keten begon 1897 (Bronx); deze vestiging draait sinds 1959 — de laatste die nog open is (gerenoveerd 2025).'),
      n('Generaties JH-families van elke herkomst kwamen hier na school, na een eerste date, na een examen.'),
      q('s10-q1'),
      n('Mehta\'s familie bestelde de Sink Sundae kort na aankomst: dít is de belofte van de Nieuwe Wereld.'),
      n('Eet samen uit één veel te grote coupe.'),
    ],
  },
}
