// Statisch host-draaiboek per stop, afgeleid uit The_Arrivals_ACHTERGROND_V2.md.
// HOOFDINFO bovenaan, daarna het verhaal als korte bullets met de vragen op hun plek.
// Belangrijk: een bullet die het antwoord verklapt staat ALTIJD ónder de vraag, niet erboven.
// `question`-beats verwijzen naar vraag-id's in de DB (group_id = stop-id).

export type PlaybookBeat = { kind: 'note'; text: string } | { kind: 'question'; id: string }

export interface StopPlaybook {
  hoofdinfo: string[]
  script: PlaybookBeat[]
}

const n = (text: string): PlaybookBeat => ({ kind: 'note', text })
const q = (id: string): PlaybookBeat => ({ kind: 'question', id })

export const STOP_PLAYBOOK: Record<string, StopPlaybook> = {
  s1: {
    hoofdinfo: [
      'Gepland project van de Queensboro Corporation (MacDougall) — niet organisch gegroeid.',
      '"Heights" = pure marketing: een plat weiland ("Trains Meadow") dat het prestige van Brooklyn Heights leende.',
      'Gebouwd voor White Anglo-Saxon Protestants; geweerd: Joden, zwarte Amerikanen, in de praktijk ook katholieken/Italianen/Grieken.',
      'De uitsluiting zat óók in het coöperatie-model: bewoners kozen zelf wie er introk.',
    ],
    script: [
      n('Tot ~1900: moerassig boerenland, ver van de stad.'),
      n('Twee dingen veranderden alles: de Queensboro Bridge (1909) + de metro (1917, de latere 7) — Manhattan op forensenafstand.'),
      n('MacDougalls Queensboro Corporation kocht het op en bouwde er een compleet merk omheen — de naam incluis.'),
      q('s1-q1'),
      n('Antwoord: "Jackson" van Jackson Avenue, "Heights" geleend van Brooklyn Heights — terwijl het terrein kurkdroog vlak is. Pure positionering.'),
      n('De innovatie: de "garden apartment" — gesloten blokken rond een verborgen binnentuin.'),
      n('Het onzichtbare wás het punt: privé, exclusief, groen achter de gevel.'),
      n('Agressief verkocht: een van de eerste radioreclames; "restricted community" als verkoopargument, niet als schaamte.'),
      q('s1-q2'),
      n('De zeef werkte op twee niveaus. Niveau 1: restrictieve aktes (covenants) — verkoop/verhuur aan bepaalde groepen verboden.'),
      n('Tijdgenoot vatte de sfeer samen als "geen katholieken, Joden of honden".'),
      q('s1-q3'),
      n('Antwoord: niveau 2, duurzamer — het coöperatie-model. De buren beslisten zélf wie introk; uitsluiting werd zelfregulerend, geen verhuurder nodig.'),
      n('Pas onafdwingbaar in 1948 (Shelley v. Kraemer); zwarte bewoners informeel geweerd tot ná de Fair Housing Act (1968).'),
      n('Verteltip: de Olmsted-tuin is "men zegt dat" — vertel als anekdote.'),
      n('Houd het mechanisme vast: deze zeef komt elke stop terug, telkens vermomd.'),
    ],
  },
  s2: {
    hoofdinfo: [
      'Scrabble bedacht door Alfred Butts (werkloze architect), ontwikkeld in de kelder van deze kerk. (1938 = "Criss-Cross Words"; naam "Scrabble" pas 1948 via James Brunot.)',
      "In de jaren '40 doorbraken Joden én homoseksuele mannen de witte utopie.",
      'Lange LGBT-traditie; het Jewish Center op 77th huisvest nu óók Hindoe-, Pinkster- en Iftar-diensten.',
    ],
    script: [
      n('De Depressie deed wat idealen niet deden: exclusiviteit werd onbetaalbaar.'),
      n('Een verhuurder kiest tussen "leeg" en "verhuurd" — en kiest verhuurd. De zeef begint te haperen.'),
      q('s2-q2'),
      n('Antwoord: twee "ongewenste" groepen tegelijk — Joodse New Yorkers (lang geweerd)...'),
      n('...én homoseksuele mannen uit Manhattan (anonimiteit + betaalbaarheid).'),
      n('Dat is de kiem van de latere grootste Latino-LGBTQ-cultuur van de stad (Stop 8).'),
      q('s2-q1'),
      n('Antwoord: Scrabble, bedacht door Alfred Butts — een architect die door de Depressie zonder werk zat.'),
      n('Eerst "Criss-Cross Words" (1938); pas in 1948 koopt James Brunot de rechten en doopt het "Scrabble".'),
      q('s2-q3'),
      n('Antwoord: hij telde de letterfrequentie van het Engels (o.a. op de voorpagina van de NYT) om de punten te bepalen.'),
      n('Daarom: de E goedkoop en talrijk, de Q en Z zeldzaam en duur.'),
      n('Eén gebouw, alle werelden: hier preekt men nu in Engels, Spaans én Mandarijn.'),
      n('Verderop het Jewish Center op 77th: nu óók Hindoe-, Pinkster- en Iftar-diensten.'),
      n('De palimpsest in religieuze vorm — dezelfde stenen, nieuwe stemmen die de ruimte delen.'),
    ],
  },
  s3: {
    hoofdinfo: [
      "Colombianen = eerste grote Latino-golf (jaren '50), lang de meest zichtbare; \"Little Colombia\" / Chapinero.",
      'Vandaag zijn Ecuadorianen de grootste groep (~16%), dan Colombianen; grote Dominicaanse, Mexicaanse en Bangladeshi-gemeenschappen.',
      'Arepa = maïskoek. Terraza 7 (Freddy Castiblanco) = cultuur als verzet tegen gentrificatie.',
      "Donkere kant: cocaïne-jaren '80 op Roosevelt; journalist Manuel de Dios Unanue vermoord (1992).",
    ],
    script: [
      n('We staan in de Latino-hoek van de buurt (rond 82nd–83rd & Roosevelt).'),
      q('s3-q1'),
      n('Antwoord: Colombianen waren de pioniers — dit was decennialang "Little Colombia" / Chapinero.'),
      q('s3-q3'),
      n('Antwoord: La Violencia (1948–58) dreef honderdduizenden Colombianen het land uit.'),
      n('JH bood drie dingen: goedkope huur, de 7-metro ("the International Express") naar werk, én ketenmigratie (de eersten haalden familie en dorpsgenoten na).'),
      n('Maar het verhaal moet schuiven: de "Colombiaanse buurt" is vooral een verhaal uit de jaren \'70–\'80.'),
      q('s3-q2'),
      n('Antwoord: vandaag zijn Ecuadorianen de grootste groep; daarnaast grote Dominicaanse, Mexicaanse en Bangladeshi-gemeenschappen.'),
      n('"Latino" is geen monoliet — de buurt dwingt nabuurschap, geen eenheid.'),
      n('Eerlijk over de schaduw: Roosevelt had in de jaren \'80 een zware reputatie in de cocaïne-economie.'),
      n('Symbool: journalist Manuel de Dios Unanue, in 1992 vermoord nadat hij het Cali-kartel blootlegde — een aanslag op de persvrijheid.'),
      n('Tot slot een hoopvol tegenbeeld, een paar meter verderop: Terraza 7 van Freddy Castiblanco.'),
      q('s3-q4'),
      n('Antwoord: hij runt het bewust als cultureel platform tegen verdringing/gentrificatie. (Opent pas ~17:00 — wijs het van buiten aan.) Proef hier de arepa.'),
    ],
  },
  s4: {
    hoofdinfo: [
      'Roosevelt Ave (onder de 7) = de informele economie: remittances (~$650 mld/jr, meer dan alle ontwikkelingshulp), valse documenten, zichtbaar sekswerk.',
      'Lorena Borjas: "moeder van de trans-Latinx-gemeenschap van Queens". Mexicaanse migrant (1981), zelf slachtoffer van mensenhandel.',
      'Decennialange outreach: condooms/spuiten, hiv-tests, borgsommen, opvang bij haar thuis.',
      '2017 gepardonneerd (campagne o.l.v. Danny Dromm); stierf maart 2020 als vroeg COVID-slachtoffer.',
    ],
    script: [
      n('Twee straten, twee werelden: 37th Ave is de nette "sidewalk ballet".'),
      n('Roosevelt is rauwer, donkerder, onder de geribbelde schaduw van de 7-trein.'),
      n('Hier draait de "informele stad" — wat de officiële stad liever niet ziet, maar die de buurt draaiend houdt.'),
      q('s4-q1'),
      n('Antwoord: remittances — migranten sturen wereldwijd ~$650 miljard per jaar naar huis.'),
      n('Méér dan het totale ontwikkelingshulpbudget van alle rijke landen samen.'),
      n('Dat geld omzeilt regeringen en corruptie — rechtstreeks naar oma\'s medicijnen of een zus\' schoolgeld.'),
      n('De geldtransferwinkels langs Roosevelt zijn de fysieke infrastructuur ervan.'),
      n('Eén vrouw belichaamt deze laag: Lorena Borjas, Mexicaanse migrant (1981), zelf slachtoffer van mensenhandel.'),
      q('s4-q2'),
      n('Antwoord: bekend als "de moeder van de trans-Latinx-gemeenschap van Queens".'),
      n('Op precies deze stoep bouwde ze decennialang een zorgnetwerk: transvrouwen, sekswerkers, ongedocumenteerden, mensen met hiv.'),
      n('Condooms, schone spuiten, hiv-tests, borgsommen, opvang bij haar thuis. In 2017 gepardonneerd; maart 2020 een van de eerste COVID-doden.'),
      n('Ze verbindt vier draden: queer geschiedenis, sekswerk, migratie en de pandemie. Vertel de straat via haar — rechten en waardigheid, geen sensatie.'),
    ],
  },
  s5: {
    hoofdinfo: [
      'Immigration & Nationality Act 1965 (Hart-Celler) schrapte de raciale quota en opende migratie uit Azië.',
      'Eerste Indiase migranten vaak hooggeschoold (artsen/ingenieurs/academici).',
      'De tweede verdiepingen = kantoortjes om het systeem te navigeren (green cards, SAT-prep, notarios).',
      'Na 9/11: Special Registration, detenties, surveillance; taxichauffeurs als doelwit; ontstaan van DRUM.',
      'De Partition (1947) verklaart de aparte India/Pakistan/Bangladesh-gemeenschappen.',
    ],
    script: [
      n('De belangrijkste wet van de dag staat aan de basis van bijna alles hier.'),
      n('Context: decennialang gold de "national origins quota" — een bijna totale blokkade van Aziaten en Zuid-/Oost-Europeanen.'),
      q('s5-q1'),
      n('Antwoord: 1965, de Immigration & Nationality Act (Hart-Celler) — schrapte de quota, voortaan beroepsvaardigheid + gezinshereniging.'),
      n('De wetgevers dachten dat het de demografie nauwelijks zou veranderen — een van de grootste misrekeningen ooit.'),
      n('Voorrang voor hooggeschoolden → de eerste Indiërs waren artsen, ingenieurs, academici. (Mehta kwam in 1977 als 14-jarige.)'),
      n('74th St werd "Little India": sari-winkels, goud (cultureel én financieel), mithai-winkels.'),
      n('Het mythische Sam & Raj: 110 én 220 volt, en geen btw als je Gujarati sprak. (Nu dicht — vertel als geschiedenis.)'),
      n('Kijk nu omhoog naar de tweede verdiepingen.'),
      q('s5-q2'),
      n('Antwoord: "rabbit warrens" vol kantoortjes — green cards, SAT-prep, belasting, notarios. Zo navigeren nieuwkomers het systeem: één betrouwbare persoon regelt álles.'),
      n('De ondergrond ligt aan de andere kant van de wereld, in 1947.'),
      q('s5-q4'),
      n('Antwoord: de Partition — Brits-Indië langs religie gesplitst (≈1 mln doden, 10–15 mln ontheemd); in 1971 scheidde Bangladesh zich af.'),
      n('Gevolg hier: nazaten van mensen die thuis aan dodelijke grenzen stonden, wonen als buren.'),
      n('En dan de laag die de rode draad het scherpst maakt: een belonging-crisis.'),
      q('s5-q3'),
      n('Antwoord: na 9/11 (2001) werd dezelfde gemeenschap die in 1965 mocht komen, plots verdacht gemaakt.'),
      n('NSEERS/Special Registration: mannen 16+ uit moslimlanden moesten zich melden — verhoor, detentie, deportatie, uiteengevallen gezinnen.'),
      n('Hate crimes stegen; Zuid-Aziatische taxichauffeurs een kwetsbaar doelwit. Hieruit ontstond hier DRUM. De zeef in zijn lelijkste vorm.'),
    ],
  },
  s6: {
    hoofdinfo: [
      'Nieuwste laag: Tibet, Nepal, Bhutan, Bangladesh. "Little Nepal" is minstens zo groot als de Tibetaanse aanwezigheid.',
      'Veel Tibetanen zijn vluchtelingen/ballingen; de Immigration Act van 1990 wees 1.000 visa toe aan ontheemde Tibetanen.',
      'Het food court was bioscoop Earle → Eagle (één letter — "het verhaal gaat dat").',
      'Diversity Plaza is sinds 2012 autovrij — het de-facto stadsplein.',
    ],
    script: [
      n('De nieuwste laag is Himalayaans: Tibet, Nepal, Bhutan.'),
      q('s6-q2'),
      n('Antwoord: veel Tibetanen kwamen niet voor kansen maar als vluchteling/balling — migratie door verlies.'),
      n('Na de Chinese annexatie van Tibet (1950) en de vlucht van de Dalai Lama (1959) ontstond een diaspora; de Immigration Act van 1990 wees 1.000 visa toe aan ontheemde Tibetanen.'),
      q('s6-q1'),
      n('Antwoord: zeg niet alleen "Tibetaans" — de Nepalese gemeenschap is minstens zo groot (een echte "Little Nepal"), plus Bhutanezen en een grote Bengaalse gemeenschap.'),
      n('Het bindende gerecht is de momo (de dumpling) — er is zelfs een jaarlijkse Momo Crawl.'),
      n('Kijk naar dit food court-gebouw — je beste palimpsest in één object.'),
      q('s6-q3'),
      n('Antwoord: vier levens — art-deco-filmpaleis The Earle (jaren \'30) → pornofilms (\'70) → Bollywood-bioscoop (\'80) → Zuid-Aziatisch food court.'),
      n('Bij de Bollywood-stap veranderde — zo gaat het verhaal — één letter: Earle werd Eagle. Eén gevel, vier economieën.'),
      n('Eet-moment: Kabab King op de hoek staat in de NYT-100 van 2026 — en in Mamdani\'s top 3.'),
      q('s6-q4'),
      n('Antwoord: volgens Mamdani moet je de biryani bestellen (rijstgerecht met kruiden, vaak langzaam gestoomd).'),
      n('De plaza zelf is sinds 2012 autovrij: schaaktafels, eetkraampjes, een dozijn talen — een vroege voorbode van de Open Street waar we eindigen.'),
    ],
  },
  s7: {
    hoofdinfo: [
      "María Piedad Cano (de Arepa Lady) begon eind jaren '80 op een straatkar; nu een restaurant — informele economie die institutionaliseert.",
      'De nieuwe zeef = gentrificatie: documentatie/kredietchecks (die ook legale migranten missen) + prijs (300k → ~1 mln).',
      'Gevolg: kelderwoningen, soms "hot beds" (bedden in shifts).',
    ],
    script: [
      n('Het optimistische verhaal: de Arepa Lady, María Piedad Cano — folklore met feiten.'),
      q('s7-q1'),
      n("Antwoord: ze bakte jarenlang 's nachts arepa's op een straatkar op Roosevelt; cultstatus → een echt restaurant (haar zonen). Informeel → reputatie → formeel."),
      q('s7-q3'),
      n('Antwoord: een arepa is een maïskoek; de arepa de choclo is van choclo (zoete jonge maïs), vaak onder een deken van gesmolten kaas.'),
      n('Maar deze stop draagt ook de keerzijde — en die is je rode draad in zijn nieuwste vorm.'),
      q('s7-q2'),
      n('Antwoord: de nieuwe zeef is gentrificatie. Garden apartments van ~300k naderen het miljoen.'),
      n('Het venijn zit niet alleen in de huur maar in documentatie — krediet, referenties, papieren die een recent gearriveerde (ook legale) migrant niet heeft.'),
      n('Gevolg: een schaduwmarkt van kelderwoningen, soms "hot beds" (bedden in shifts).'),
      n('Maak de cirkel met Stop 1 hardop: 1910 een coöperatie-stemming, 2026 een kredietscore — dezelfde machine, ander pak.'),
    ],
  },
  s8: {
    hoofdinfo: [
      'In 1990 werd Julio Rivera (29, homoseksuele barman) door skinheads vermoord — een beruchte hate crime.',
      'Eruit ontstond de Queens Pride Parade, opgericht door buurtbewoner/leraar Danny Dromm (later raadslid).',
      'Queer lijn: Rivera (1990) → Lorena Borjas (2020), dertig jaar op dezelfde straten.',
    ],
    script: [
      n("Het dieptepunt: late jaren '80/vroege '90 — criminaliteit, stedelijk verval, de aidsepidemie."),
      n('Op deze hoek gebeurde in 1990 iets dat de gemeenschap mobiliseerde.'),
      q('s8-q1'),
      n('Antwoord: Julio Rivera (29, homoseksuele barman) werd naar een schoolplein gelokt en door skinheads vermoord, enkel omdat hij homo was — een van de eerste anti-homo hate crime zaken.'),
      n('Eruit groeide de Queens Pride Parade (eerste editie 1993), mede opgericht door leraar Danny Dromm.'),
      n('Dezelfde Dromm die later het pardon van Lorena Borjas (Stop 4) bevocht — één queer lijn, dertig jaar.'),
      q('s8-q2'),
      n('Antwoord: vandaag de op één na grootste Pride van de stad én de grootste concentratie Latino-LGBTQ-bars — in een buurt met óók zeer conservatieve gemeenschappen.'),
      n('Het eerlijke punt (Mehta): geen plotselinge liefde, maar "het zakken van de wapens". Een buurt die iemand vermoordde om wie hij was, viert hem nu.'),
    ],
  },
  s9: {
    hoofdinfo: [
      'Jackson Heights was voorjaar 2020 het epicentrum van de COVID-uitbraak in NYC.',
      'Uit de crisis groeide de 34th Avenue Open Street (±2 mijl autovrij) — "de eerste superblock van New York".',
      'Van afgeschermde privételuin (1910) naar heroverde publieke straat (2020): het hele verhaal in één gebaar.',
      'Dit is het slot — sluit af met de slotvraag en laat de groep het laatste woord.',
    ],
    script: [
      n('We eindigen op de 34th Ave Open Street — ±2 mijl dagelijks autovrij. Deze straat is geboren uit een crisis.'),
      q('s9-q1'),
      n('Antwoord: de pandemie — tijdens de lockdown van 2020 opende de stad straten als veilige buitenruimte.'),
      n('Maar 2020 sloeg hier ongekend hard toe: Jackson Heights werd het epicentrum van de stad.'),
      q('s9-q2'),
      n('Antwoord: dichtheid (gedeelde kelders maakten isoleren onmogelijk) + beroep (essentiële werkers die niet konden thuiswerken).'),
      n('Elmhurst Hospital werd het nationale symbool; koelwagens als mortuaria. Borjas stierf in deze weken.'),
      n('En precies hier vocht de gemeenschap iets hoopvols af: bewoners breidden de Open Street uit — kinderen leren fietsen, senioren met klapstoelen, spontane Zumba. "De eerste superblock van New York".'),
      n('De cirkel sluit — het mooiste geografische gebaar van de tour:'),
      n('1910 ontworpen rond verborgen privétuinen (groen als exclusief bezit); 100 jaar later de straat zélf heroverd als gedeelde publieke ruimte. Privé → publiek.'),
      n('Sluit af zonder moraal — laat de groep praten:'),
      q('s9-q3'),
    ],
  },
  s10: {
    hoofdinfo: [
      'Optioneel — de tour sluit inhoudelijk af bij Stop 9; Jahn\'s is een bonus met ijs.',
      'Jahn\'s: de keten begon 1897 (Bronx); deze vestiging draait sinds 1959 en is de laatste die nog open is (gerenoveerd 2025).',
      'Handelsmerk: de Kitchen Sink Sundae for eight — alleen samen op te eten.',
    ],
    script: [
      n('De gemeenschappelijke noemer onder alle lagen van de buurt.'),
      n('Keten begon 1897 (Bronx); deze vestiging draait sinds 1959 — de laatste die nog open is (gerenoveerd 2025).'),
      n('Generaties JH-families van elke herkomst kwamen hier na school, na een eerste date, na een examen.'),
      q('s10-q1'),
      n('Antwoord: je krijgt de Kitchen Sink Sundae alleen samen leeg — net als de buurt, die functioneert doordat mensen die elkaar niet kozen tóch dezelfde ruimte delen.'),
      n('Mehta\'s familie bestelde hem kort na aankomst: dít is de belofte van de Nieuwe Wereld. Eet samen uit één veel te grote coupe.'),
    ],
  },
}
