-- =============================================================================
-- The Arrivals - 0005: 52 losse oefen-meerkeuzevragen als warm-up-vragen.
-- Bron: practice_questions.json (geografie/migratie/talen). Komen bovenop de
-- bestaande warm-up-vragen (group_id = 'warmup').
--   * Juiste antwoorden gelijkmatig over A/B/C/D verdeeld (13 per positie).
--   * Te 'makkelijke' vragen herschreven zodat het juiste antwoord niet opvalt.
--   * De uitleg staat in model_answer en wordt na het antwoorden getoond.
-- Draai dit in de Supabase SQL Editor. Idempotent: upsert op id.
-- =============================================================================

insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-geo-01', 'warmup', 'mc', 'Wat is de hoofdstad van Canada?', '["Vancouver","Montreal","Toronto","Ottawa"]'::jsonb, 3, 'Veel mensen gokken Toronto, maar de hoofdstad is Ottawa.', 1, false, false, 100, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-geo-02', 'warmup', 'mc', 'Welke rivier vormt een groot deel van de grens tussen de VS en Mexico (en heet in Mexico de Río Bravo)?', '["Rio Grande","Mississippi","Hudson","Colorado"]'::jsonb, 0, 'De Rio Grande / Río Bravo: één rivier, twee namen, één grens.', 1, false, false, 101, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-geo-03', 'warmup', 'mc', 'Welk land heeft sinds 2023 de meeste inwoners ter wereld?', '["Indonesië","Verenigde Staten","India","China"]'::jsonb, 2, 'India haalde China in 2023 in als volkrijkste land.', 1, false, false, 102, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-geo-04', 'warmup', 'mc', 'Wat is het kleinste land ter wereld?', '["Monaco","Vaticaanstad","Liechtenstein","San Marino"]'::jsonb, 1, 'Vaticaanstad is met ongeveer 0,44 km² het kleinste land ter wereld.', 1, false, false, 103, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-geo-05', 'warmup', 'mc', 'Hoeveel officiële tijdzones telt Rusland?', '["7","5","24","11"]'::jsonb, 3, 'Rusland strekt zich uit over 11 tijdzones - van Kaliningrad tot Kamtsjatka.', 1, false, false, 104, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-geo-06', 'warmup', 'mc', 'Welke van deze hoofdsteden ligt het hoogst (boven zeeniveau)?', '["Bogotá","Mexico-Stad","La Paz","Quito"]'::jsonb, 2, 'La Paz (Bolivia) ligt op zo''n 3.600 m - de feitelijke regeringszetel die het hoogst ligt.', 1, false, false, 105, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-geo-07', 'warmup', 'mc', 'Welk werelddeel telt de meeste landen?', '["Azië","Afrika","Europa","Zuid-Amerika"]'::jsonb, 1, 'Afrika telt 54 erkende landen - meer dan welk ander continent ook.', 1, false, false, 106, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-geo-08', 'warmup', 'mc', 'Op welke twee werelddelen ligt de stad Istanbul?', '["Europa & Azië","Azië & Afrika","Azië & Oceanië","Europa & Afrika"]'::jsonb, 0, 'De Bosporus splitst Istanbul in een Europees en een Aziatisch deel.', 1, false, false, 107, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-geo-09', 'warmup', 'mc', 'Welk land grenst aan de meeste andere landen (14, samen met Rusland)?', '["Duitsland","Brazilië","India","China"]'::jsonb, 3, 'China grenst aan 14 landen - gelijk met Rusland het wereldrecord.', 1, false, false, 108, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-geo-10', 'warmup', 'mc', 'Wat is de hoofdstad van Australië?', '["Perth","Melbourne","Canberra","Sydney"]'::jsonb, 2, 'Canberra werd als compromis gekozen tussen rivalen Sydney en Melbourne.', 1, false, false, 109, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-geo-11', 'warmup', 'mc', 'Wat is de grootste warme woestijn ter wereld?', '["Kalahari","Gobi","Atacama","Sahara"]'::jsonb, 3, 'De Sahara is de grootste warme woestijn (de allergrootste woestijn is overigens koud: Antarctica).', 1, false, false, 110, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-geo-12', 'warmup', 'mc', 'Welk land staat bekend als ''het land van duizend meren''?', '["Canada","Finland","Noorwegen","Zweden"]'::jsonb, 1, 'Finland heeft er zelfs veel meer dan duizend - ruim 180.000 meren.', 1, false, false, 111, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-geo-13', 'warmup', 'mc', 'De Bosporus verbindt de Zwarte Zee met welke zee?', '["Egeïsche Zee","Marmarazee","Middellandse Zee","Adriatische Zee"]'::jsonb, 1, 'De Bosporus mondt uit in de Marmarazee, die via de Dardanellen verder naar de Egeïsche Zee leidt.', 1, false, false, 112, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-geo-14', 'warmup', 'mc', 'Wat is de hoofdstad van Brazilië?', '["Brasília","Salvador","Rio de Janeiro","São Paulo"]'::jsonb, 0, 'Brasília werd in 1960 vanuit het niets gebouwd als nieuwe hoofdstad in het binnenland.', 1, false, false, 113, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-geo-15', 'warmup', 'mc', 'Welk land heeft als enige ter wereld een vlag die niet rechthoekig is?', '["Vaticaanstad","Nepal","Bhutan","Zwitserland"]'::jsonb, 1, 'Nepals vlag bestaat uit twee gestapelde wimpels - uniek in de wereld.', 1, false, false, 114, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-geo-16', 'warmup', 'mc', 'Welke twee landen delen ''s werelds langste landgrens?', '["India & China","VS & Canada","Rusland & China","Argentinië & Chili"]'::jsonb, 1, 'De grens tussen de VS en Canada is met ruim 8.800 km de langste ter wereld.', 1, false, false, 115, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-geo-17', 'warmup', 'mc', 'Wat is de kleurvolgorde van de Colombiaanse vlag, van boven naar onder?', '["Rood-wit-blauw","Geel-blauw-rood","Blauw-wit-blauw","Groen-geel-rood"]'::jsonb, 1, 'Geel (rijkdom), blauw (de zeeën) en rood (het bloed van de helden).', 1, false, false, 116, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-mig-01', 'warmup', 'mc', 'Op welk eiland bij New York werden tussen 1892 en 1954 miljoenen immigranten geregistreerd?', '["Roosevelt Island","Governors Island","Liberty Island","Ellis Island"]'::jsonb, 3, 'Via Ellis Island kwamen meer dan 12 miljoen immigranten de VS binnen.', 1, false, false, 117, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-mig-02', 'warmup', 'mc', 'Wat betekent het woord ''diaspora'' oorspronkelijk?', '["Terugkeer naar het vaderland","Versmelting tot één volk","Verspreiding of verstrooiing","Een streng bewaakte grens"]'::jsonb, 2, 'Van het Griekse ''diaspeirein'' - uitzaaien, verstrooien.', 1, false, false, 118, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-mig-03', 'warmup', 'mc', 'Welk land heeft (in absolute aantallen) de grootste immigrantenbevolking ter wereld?', '["Duitsland","Verenigde Staten","Saoedi-Arabië","Verenigd Koninkrijk"]'::jsonb, 1, 'De VS tellen zo''n 50 miljoen in het buitenland geboren inwoners - veruit de meeste.', 1, false, false, 119, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-mig-04', 'warmup', 'mc', 'De Amerikaanse ''Great Migration'' verwees naar de verhuizing van welke groep?', '["Mexicaanse arbeiders naar de velden van Californië","Italiaanse families naar Lower Manhattan","Afro-Amerikanen van het Zuiden naar het Noorden","Ierse katholieken naar de steden van New England"]'::jsonb, 2, 'Tussen 1916 en 1970 trokken miljoenen zwarte Amerikanen weg uit het Zuiden.', 1, false, false, 120, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-mig-05', 'warmup', 'mc', 'Welke ramp dreef in de jaren 1840 massale Ierse emigratie naar de VS?', '["De aardappelhongersnood","Een verwoestende pestepidemie","Een langdurige burgeroorlog","Een reeks vulkaanuitbarstingen"]'::jsonb, 0, 'De Great Famine kostte circa een miljoen levens en dreef er nog eens een miljoen het land uit.', 1, false, false, 121, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-mig-06', 'warmup', 'mc', 'Wat onderscheidt een vluchteling juridisch vooral van een ''gewone'' migrant?', '["Een vluchteling vertrekt altijd vrijwillig","Een vluchteling heeft per definitie geen papieren","Een vluchteling is altijd jonger dan een migrant","Een vluchteling vlucht voor vervolging of gevaar"]'::jsonb, 3, 'Het Vluchtelingenverdrag (1951) draait om gegronde vrees voor vervolging.', 1, false, false, 122, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-mig-07', 'warmup', 'mc', 'Welke VN-organisatie houdt zich bezig met vluchtelingen?', '["UNHCR","UNICEF","WHO","UNESCO"]'::jsonb, 0, 'De UNHCR is het vluchtelingenagentschap van de VN.', 1, false, false, 123, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-mig-08', 'warmup', 'mc', 'Hoeveel sturen migranten naar schatting jaarlijks naar lage- en middeninkomenslanden (remittances)?', '["~650 miljard dollar","~65 miljard dollar","~6 miljard dollar","~6,5 biljoen dollar"]'::jsonb, 0, 'Rond de 650 miljard dollar per jaar - meer dan alle ontwikkelingshulp samen.', 1, false, false, 124, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-mig-09', 'warmup', 'mc', 'Welke Canadese stad geldt als een van de meest multiculturele ter wereld, met ruim de helft van de inwoners buiten Canada geboren?', '["Halifax","Calgary","Toronto","Winnipeg"]'::jsonb, 2, 'In Toronto is meer dan de helft van de inwoners elders geboren.', 1, false, false, 125, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-mig-10', 'warmup', 'mc', 'De term ''smeltkroes'' (melting pot) werd vooral populair voor welke plek?', '["De VS, met name New York","Egypte, met name Caïro","Japan, met name Tokio","Duitsland, met name Berlijn"]'::jsonb, 0, 'Het beeld werd beroemd door een toneelstuk uit 1908 over immigranten in New York.', 1, false, false, 126, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-mig-11', 'warmup', 'mc', 'Welk land heeft de grootste diaspora ter wereld (meeste in het buitenland wonende landgenoten)?', '["India","China","Rusland","Mexico"]'::jsonb, 0, 'India heeft met circa 18 miljoen emigranten de grootste diaspora.', 1, false, false, 127, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-mig-12', 'warmup', 'mc', 'Wat betekent ''ketenmigratie'' (chain migration)?', '["Migratie die per boot wordt afgelegd","Tijdelijke seizoensarbeid in het buitenland","Een door de staat gedwongen verhuizing","Migranten halen familie en bekenden na"]'::jsonb, 3, 'De eerste aankomers vormen een anker dat de volgende migranten aantrekt - zo ontstaan buurten.', 1, false, false, 128, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-mig-13', 'warmup', 'mc', 'Welke muur viel in 1989 en veranderde migratie in Europa ingrijpend?', '["De Westmuur","De Muur van Hadrianus","De Berlijnse Muur","De Chinese Muur"]'::jsonb, 2, 'De val van de Berlijnse Muur opende het Oostblok.', 1, false, false, 129, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-mig-14', 'warmup', 'mc', 'Het Vrijheidsbeeld in New York was een geschenk van welk land?', '["Italië","Nederland","Frankrijk","Engeland"]'::jsonb, 2, 'Een geschenk van Frankrijk in 1886, symbool van vrijheid voor aankomende immigranten.', 1, false, false, 130, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-mig-15', 'warmup', 'mc', 'Op de sokkel van het Vrijheidsbeeld staat het gedicht ''The New Colossus''. Wie schreef het?', '["Emma Lazarus","Walt Whitman","Maya Angelou","Langston Hughes"]'::jsonb, 0, 'Emma Lazarus schreef de beroemde regel ''Give me your tired, your poor...''.', 1, false, false, 131, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-mig-16', 'warmup', 'mc', 'Wie is een ''eerste generatie'' immigrant?', '["Een toerist","Het in het nieuwe land geboren kind van migranten","Iemand die zelf naar een nieuw land migreerde","Iedere staatsburger"]'::jsonb, 2, 'De persoon die zelf migreerde; hun kinderen heten doorgaans de tweede generatie.', 1, false, false, 132, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-mig-17', 'warmup', 'mc', 'Uit welk deel van Italië kwam tussen 1880 en 1920 het leeuwendeel van de emigranten naar de VS?', '["Toscane en Midden-Italië","Veneto en de Alpenstreek","Lombardije en het noorden","Zuid-Italië en Sicilië"]'::jsonb, 3, 'Armoede in de Mezzogiorno dreef miljoenen Zuid-Italianen en Sicilianen overzee.', 1, false, false, 133, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-mig-18', 'warmup', 'mc', 'Het ''Bracero''-programma bracht tijdelijke arbeidsmigranten naar de VS uit welk land?', '["Polen","China","Filipijnen","Mexico"]'::jsonb, 3, 'Van 1942 tot 1964 werkten miljoenen Mexicaanse ''braceros'' in de Amerikaanse landbouw.', 1, false, false, 134, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-tal-01', 'warmup', 'mc', 'Welke taal heeft wereldwijd de meeste moedertaalsprekers?', '["Mandarijn-Chinees","Spaans (Castiliaans)","Hindi-Urdu","Engels"]'::jsonb, 0, 'Mandarijn heeft de meeste moedertaalsprekers; Engels wint pas als je tweede taal meetelt.', 1, false, false, 135, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-tal-02', 'warmup', 'mc', 'Welke taal heeft in totaal de meeste sprekers (moedertaal + tweede taal)?', '["Mandarijn","Engels","Spaans","Arabisch"]'::jsonb, 1, 'Engels telt in totaal ruim anderhalf miljard sprekers wereldwijd.', 1, false, false, 136, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-tal-03', 'warmup', 'mc', 'Hoeveel talen worden er wereldwijd naar schatting gesproken?', '["~70.000","~700","~70","~7.000"]'::jsonb, 3, 'Ongeveer 7.000 - en een groot deel daarvan wordt met uitsterven bedreigd.', 1, false, false, 137, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-tal-04', 'warmup', 'mc', 'Tot welke taalfamilie behoren Spaans en Italiaans?', '["Semitische talen","Germaanse talen","Slavische talen","Romaanse talen"]'::jsonb, 3, 'Beide stammen af van het Latijn - vandaar ''Romaans''.', 1, false, false, 138, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-tal-05', 'warmup', 'mc', 'Welke van deze talen is GEEN Indo-Europese taal?', '["Russisch","Frans","Fins","Grieks"]'::jsonb, 2, 'Fins is Fins-Oegrisch, verwant aan Estisch en Hongaars - niet aan zijn buurtalen.', 1, false, false, 139, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-tal-06', 'warmup', 'mc', 'In welk schrift wordt het Hindi geschreven?', '["Arabisch","Devanagari","Hangul","Cyrillisch"]'::jsonb, 1, 'Devanagari wordt ook voor Sanskriet, Marathi en Nepali gebruikt.', 1, false, false, 140, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-tal-07', 'warmup', 'mc', 'In ongeveer hoeveel landen is Spaans een officiële taal?', '["~40","~10","~5","~20"]'::jsonb, 3, 'Ongeveer twintig landen, vooral in Latijns-Amerika plus Spanje en Equatoriaal-Guinea.', 1, false, false, 141, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-tal-08', 'warmup', 'mc', 'Tot welke taaltak behoort het Nederlands?', '["West-Germaans","Romaanse talen","Keltische talen","Slavische talen"]'::jsonb, 0, 'Nederlands is West-Germaans, nauw verwant aan Duits, Fries en Engels.', 1, false, false, 142, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-tal-09', 'warmup', 'mc', 'Welke taal is officieel in Brazilië?', '["Frans","Portugees","Braziliaans","Spaans"]'::jsonb, 1, 'Brazilië is het grootste Portugeessprekende land ter wereld.', 1, false, false, 143, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-tal-10', 'warmup', 'mc', '''Hangul'' is het alfabet van welke taal?', '["Koreaans","Vietnamees","Japans","Thais"]'::jsonb, 0, 'Hangul werd in de 15e eeuw bewust ontworpen om lezen voor iedereen makkelijk te maken.', 1, false, false, 144, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-tal-11', 'warmup', 'mc', 'Welke van deze talen schrijft men van rechts naar links?', '["Hindi","Swahili","Arabisch","Mandarijn"]'::jsonb, 2, 'Arabisch (net als Hebreeuws) wordt van rechts naar links geschreven.', 1, false, false, 145, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-tal-12', 'warmup', 'mc', 'Esperanto is een voorbeeld van een...?', '["Een bewust bedachte kunsttaal","Een regionaal dialect","Een uitgestorven dode taal","Een internationale gebarentaal"]'::jsonb, 0, 'Esperanto werd eind 19e eeuw ontworpen door L.L. Zamenhof als neutrale wereldtaal.', 1, false, false, 146, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-tal-13', 'warmup', 'mc', 'Welke taal is in de meeste landen ter wereld een officiële taal?', '["Frans","Engels","Arabisch","Spaans"]'::jsonb, 1, 'Engels heeft in ruim vijftig landen een officiële status - meer dan welke taal ook.', 1, false, false, 147, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-tal-14', 'warmup', 'mc', 'Quechua, de taal van het Inca-rijk, wordt vandaag vooral nog gesproken in welke regio?', '["De kusten van Centraal-Amerika","De eilanden van de Cariben","De Andes van Zuid-Amerika","De delta van de Amazone"]'::jsonb, 2, 'Miljoenen mensen in de Andes spreken nog steeds Quechua.', 1, false, false, 148, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-tal-15', 'warmup', 'mc', 'Welke taal gebruikt windrichtingen in plaats van ''links'' en ''rechts'' (een beroemd voorbeeld)?', '["Het Europees Portugees","Een afgelegen Scandinavische streektaal","Een Australische Aboriginal-taal","Het hedendaagse Frans"]'::jsonb, 2, 'Sprekers zeggen letterlijk ''er zit een mier op je noordwestelijke been'' - en hebben een toprichtingsgevoel.', 1, false, false, 149, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-tal-16', 'warmup', 'mc', 'Wat betekent ''code-switching''?', '["Een geheime taal met je eigen groep spreken","Wisselen tussen talen binnen één gesprek","Een tekst van de ene taal naar de andere vertalen","Een eerder geleerde taal langzaam verleren"]'::jsonb, 1, 'Veel meertalige mensen wisselen moeiteloos van taal midden in een zin.', 1, false, false, 150, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('pr-tal-17', 'warmup', 'mc', 'Het Jiddisch is historisch vooral gebaseerd op welke taal?', '["Pools met Duitse leenwoorden","Russisch, met Duitse en Jiddische leenwoorden","Uitsluitend klassiek Hebreeuws","Duits, met Hebreeuwse en Slavische invloeden"]'::jsonb, 3, 'Jiddisch ontstond uit Middelhoogduits, geschreven in Hebreeuws schrift, met leenwoorden uit het Hebreeuws en Slavische talen.', 1, false, false, 151, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
