-- =============================================================================
-- The Arrivals - 0005: volledige warm-up-vragenpool.
-- Alle quizvragen (oorspronkelijke warm-up + alle stop-vragen) staan hier als
-- warm-up-vragen (group_id = 'warmup'). Stop-vragen kregen een nieuw id met
-- prefix 'wu-' zodat de live-tour-vragen ongemoeid blijven.
-- Meerkeuze: juiste antwoorden verspreid over de posities, afleiders qua lengte
-- en nuance gelijkgetrokken. Draai dit in de Supabase SQL Editor.
-- Idempotent: upsert op id, opnieuw draaien is veilig.
-- =============================================================================

insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-q1', 'warmup', 'mc', 'In welk stadsdeel van New York ligt Jackson Heights?', '["Brooklyn","Manhattan","Queens","The Bronx"]'::jsonb, 2, null, 1, false, false, 0, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-q2', 'warmup', 'mc', 'Hoeveel talen worden er naar schatting in Jackson Heights gesproken?', '["Rond de 40","Meer dan 160","Rond de 90","Meer dan 280"]'::jsonb, 1, null, 1, false, false, 1, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-q3', 'warmup', 'mc', 'Welke metrolijn heet ''the International Express''?', '["De 1","De A","De L","De 7"]'::jsonb, 3, null, 1, false, false, 2, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-q4', 'warmup', 'mc', 'Wat is een ''palimpsest''?', '["Perkament dat is afgekrabd en opnieuw beschreven, met de oude tekst eronder","Een oude landkaart waarop allang verdwenen straten nog vaag doorschemeren","Een muur waarop oude en nieuwe affiches jarenlang over elkaar heen plakken","Een gerecht waarin de restjes van eerdere dagen telkens opnieuw verwerkt worden"]'::jsonb, 0, null, 1, false, false, 3, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-s1-q2', 'warmup', 'mc', 'Welke groepen mochten hier oorspronkelijk volgens de aktes niet wonen?', '["Ieren en Italiaanse katholieken","Aziatische en Latijns-Amerikaanse migranten","Arbeiders zonder vast inkomen","Joden en zwarte Amerikanen"]'::jsonb, 3, null, 1, false, false, 4, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-s2-q2', 'warmup', 'mc', 'Welke twee groepen ''lekten'' als eerste de witte utopie binnen in de jaren ''40?', '["Colombiaanse en Mexicaanse nieuwkomers","Tibetaanse en Nepalese families uit de Himalaya","Joodse New Yorkers en homoseksuele mannen","Ierse en Italiaanse fabrieksarbeiders"]'::jsonb, 2, null, 1, false, false, 5, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-s3-q1', 'warmup', 'mc', 'Welke Latino-gemeenschap kwam als eerste, en in welk decennium?', '["Mexicanen, jaren ''90","Colombianen, jaren ''50","Dominicanen, jaren ''70","Ecuadorianen, jaren ''80"]'::jsonb, 1, null, 1, false, false, 6, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-s3-q2', 'warmup', 'mc', 'Proef de arepa. Van welk graan is hij gemaakt?', '["Tarwe","Rijst","Gerst","Maïs"]'::jsonb, 3, null, 1, false, false, 7, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-s4-q2', 'warmup', 'mc', 'Welk type beroep hadden veel van de eerste Indiase migranten, en waarom?', '["Landarbeiders, omdat er volop vraag was naar seizoenswerk op het land","Artsen en ingenieurs, want de wet gaf voorrang aan hooggeschoolden","Zeelieden, aangemonsterd via de haven van New York","Studenten, via een internationaal uitwisselingsprogramma"]'::jsonb, 1, null, 1, false, false, 8, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-s4-q3', 'warmup', 'mc', 'Welke gebeurtenis maakte India en Pakistan in 1947 tot aparte landen?', '["Het einde van de Tweede Wereldoorlog","De oprichting van de Verenigde Naties","De Partition van Brits-Indië","Een militaire staatsgreep in Delhi"]'::jsonb, 2, null, 1, false, false, 9, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-s5-q2', 'warmup', 'mc', 'Veel Tibetanen hier zijn niet zomaar migranten, maar iets specifiekers. Wat?', '["Vluchtelingen en politieke ballingen","Uitgenodigde gastarbeiders uit de regio","Studenten op een uitwisseling","Seizoensarbeiders in de horeca"]'::jsonb, 0, null, 1, false, false, 10, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-s6-q1', 'warmup', 'mc', 'Hoe verkocht de Arepa Lady (María Piedad Cano) haar arepa''s oorspronkelijk?', '["Vanuit een klein eethuis","Op de wekelijkse Greenmarket","Vanaf een straatkar op de hoek","Met een bestelbus langs de deur"]'::jsonb, 2, null, 1, false, false, 11, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-s8-q1', 'warmup', 'mc', 'Tijdens welke wereldgebeurtenis werd deze straat een ''superblock''?', '["De COVID-pandemie (2020)","De aanslagen van 9/11 (2001)","De financiële crisis (2008)","Orkaan Sandy (2012)"]'::jsonb, 0, null, 1, false, false, 12, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-q5', 'warmup', 'open', 'Wat verwacht je van een buurt met meer dan 160 talen? Schrijf in één zin wat je nieuwsgierig maakt.', null, null, 'Geen goed/fout - beoordeel op betrokkenheid; iedereen die iets zinnigs schrijft verdient het punt.', 1, false, false, 13, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-s1-q1', 'warmup', 'open', 'Deze buurt heet ''Heights''. Hoe hoog ligt het hoogste punt, en waarom heet het dan zo?', null, null, 'Het is plat (oud weiland ''Trains Meadow''); ''Heights'' is marketing om prestige te suggereren.', 1, false, false, 14, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-s2-q1', 'warmup', 'open', 'Welk wereldberoemd bordspel is hier in 1938 bedacht, en wat was het beroep van de bedenker?', null, null, 'Scrabble; de bedenker (Alfred Butts) was een werkloze architect.', 1, false, false, 15, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-s3-q3', 'warmup', 'open', 'Terraza-eigenaar Freddy Castiblanco noemt zijn zaak ''verzet''. Verzet tegen wat?', null, null, 'Tegen gentrificatie / verdringing van de gemeenschap.', 1, false, false, 16, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-s4-q1', 'warmup', 'open', 'Eén wet uit één jaar verklaart bijna alle migratie hier. Welk jaar, en wat deed die wet?', null, null, '1965, de Immigration & Nationality Act (Hart-Celler): schrapte de raciale nationale quota en opende migratie uit Azië.', 1, false, false, 17, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-s5-q1', 'warmup', 'open', 'Dat filmpaleis heette ''The Earle'', daarna ''The Eagle''. Wat veranderden de eigenaren, en waarom maar dát?', null, null, 'Eén letter (Earle naar Eagle), om kosten te sparen; ze wilden niet in een heel nieuw bord investeren.', 1, false, false, 18, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-s6-q2', 'warmup', 'open', 'Een oud-stadsplanner vergeleek gentrificatie met cholesterol. Wat bedoelde ze?', null, null, 'Dat er goede én slechte gentrificatie bestaat (goede = inkomensdiversiteit; slechte = verdringing).', 1, false, false, 19, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('wu-s7-q1', 'warmup', 'open', 'Naar wie is de hoek 78th St & 37th Ave vernoemd, en welke jaarlijkse gebeurtenis komt voort uit zijn dood in 1990?', null, null, 'Julio Rivera; de Queens Pride Parade (opgericht door Danny Dromm).', 1, false, false, 20, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=excluded.active;
