-- =============================================================================
-- The Arrivals - 0006: content v2 (11 stops, herziene rode draad, feitcorrecties).
-- Vervangt alle tour-content; warm-up (incl. 52 oefenvragen), cards en sessies
-- blijven ongemoeid. Draai dit in de Supabase SQL Editor. Idempotent.
-- =============================================================================

-- 1. Nieuwe meta-kolommen
alter table app_settings add column if not exists red_thread text;
alter table app_settings add column if not exists mechanism text;
alter table app_settings add column if not exists land_acknowledgement text;

-- 2. Admin-RPC uitbreiden met de nieuwe meta-velden
create or replace function admin_update_settings(p_secret text, p_row jsonb)
returns void language plpgsql security definer set search_path = public as $$
begin
  perform assert_admin(p_secret);
  update app_settings set
    title=coalesce(p_row->>'title',title), subtitle=p_row->>'subtitle',
    date=p_row->>'date', central_question=p_row->>'central_question',
    red_thread=p_row->>'red_thread', mechanism=p_row->>'mechanism',
    land_acknowledgement=p_row->>'land_acknowledgement',
    opening_line=p_row->>'opening_line', closing_line=p_row->>'closing_line',
    warmup_intro=coalesce(p_row->>'warmup_intro',warmup_intro),
    mc_points=coalesce(nullif(p_row->>'mc_points','')::int,mc_points),
    open_points=coalesce(nullif(p_row->>'open_points','')::int,open_points),
    timeline_note=p_row->>'timeline_note'
  where id=1;
end;
$$;

-- 3. Herziene meta (warmup_intro blijft staan)
update app_settings set
  title = 'The Arrivals - Jackson Heights',
  subtitle = 'Een quiz-wandeling door honderd jaar migratie',
  date = '2026-06-21',
  central_question = 'Van wie is deze buurt - en wie mag dat bepalen?',
  red_thread = 'Van wie is deze buurt - en wie mag dat bepalen?',
  mechanism = 'Uitsluiting vindt zichzelf telkens opnieuw uit: akte (1910) -> co-op-zeef -> redlining -> kredietcheck -> Special Registration (2001) -> huurprijs.',
  land_acknowledgement = 'Lang voor de eerste makelaar was dit land van de Lenape. Elke laag is over een vorige heen geschreven - die eerste verdwijning incluis.',
  opening_line = 'We lopen vandaag door honderd jaar. Maar onder elke laag ligt dezelfde vraag: van wie is deze buurt - en wie mag dat bepalen? Deze plek is gebouwd om mensen buiten te houden. Hoe werd het dan de meest diverse plek op aarde?',
  closing_line = 'Je hebt de wereld doorkruist zonder te vliegen. Van wie is deze buurt nu - en wie bepaalt dat morgen?',
  timeline_note = 'De ''Tijdlijn''-vragen (isTimeline:true) vormen de scorende kern; kies er 6-8 uit. Overige vragen geven bonuspunten.',
  mc_points = 1,
  open_points = 2
where id = 1;

-- 4. Oude tour-vragen en activiteiten wissen
delete from questions where group_id like 's%';
delete from activities;

-- 5. Stops (v2)
insert into stops (id, number, name, optional, location, era, layer, food, intro, reveal, background, sort_order) values ('s0', 0, 'Cannelle Patisserie', true, '75-59 31st Ave', 'Het heden', 'Vóór de tijdreis', 'Croissant', 'Voor we 100 jaar teruggaan, beginnen we in het heden. Pak een croissant en kijk om je heen in de rij.', 'Een Franse bakkerij, de hele wereld in de rij voor dezelfde croissant. Geen festival, geen folder. Onthoud dit beeld.', 'Het ''antwoord'' van vandaag op de vraag die de hele tour stelt - om daarna terug te spoelen naar 1910.', 0)
  on conflict (id) do update set number=excluded.number, name=excluded.name, optional=excluded.optional, location=excluded.location, era=excluded.era, layer=excluded.layer, food=excluded.food, intro=excluded.intro, reveal=excluded.reveal, background=excluded.background, sort_order=excluded.sort_order;
insert into stops (id, number, name, optional, location, era, layer, food, intro, reveal, background, sort_order) values ('s1', 1, 'The Chateau - De Utopie', false, '81st St & 34th Ave', '1910s', '1 · Utopie', null, 'Welkom op de vlakste ''Heights'' van New York. We staan nu al op de 34th Avenue Open Street - onthoud deze straat, we eindigen hier. (Spreek eerst de Lenape-zin en de openingsregel uit.)', 'Geen heuvel: dit was ''Trains Meadow''. ''Heights'' echode het prestige van Brooklyn Heights; ''Jackson'' komt van Jackson Avenue (nu Northern Blvd). De Queensboro Corporation muntte ''garden apartment'' - blokken rond een verborgen binnentuin, privé en exclusief. De uitsluiting zat óók in het coöperatie-model: bewoners bepaalden zelf wie hun buren werden. Diezelfde architectuur huisvest nu de meest diverse populatie ter wereld.', 'Geïnspireerd op Ebenezer Howards Garden City en Berlijnse tuinappartementen. Restrictieve aktes werden pas in 1948 (Shelley v. Kraemer) onafdwingbaar; informele uitsluiting van zwarte bewoners liep door tot na 1968. De Olmsted-tuin is een onbevestigd verhaal.', 1)
  on conflict (id) do update set number=excluded.number, name=excluded.name, optional=excluded.optional, location=excluded.location, era=excluded.era, layer=excluded.layer, food=excluded.food, intro=excluded.intro, reveal=excluded.reveal, background=excluded.background, sort_order=excluded.sort_order;
insert into stops (id, number, name, optional, location, era, layer, food, intro, reveal, background, sort_order) values ('s2', 2, 'Methodist Church (+ Jewish Center) - De Eerste Scheuren', false, '81-10 35th Ave (Jewish Center: 77th St)', '1930s-50s', '2 · Scheuren', null, 'In dit doodgewone kerkgebouw is in de jaren ''30 iets bedacht dat in honderden miljoenen huiskamers belandde. Hint: taal + een man zonder baan.', 'Scrabble - door Alfred Butts, een werkloze architect, ontwikkeld in deze kerkkelder (in 1938 nog ''Criss-Cross Words''; de naam ''Scrabble'' kwam in 1948 via James Brunot). Deze kerk heeft een lange LGBT-activismetraditie en preekt nu in Engels, Spaans en Mandarijn. Het Jewish Center op 77th huisvest inmiddels óók Hindoe-, Pinkster- en Iftar-diensten.', 'De Depressie maakte exclusiviteit onbetaalbaar; de ''zeef'' brokkelde af. Butts bepaalde de letterpunten via frequentie-analyse van NYT-voorpagina''s (vandaar de dure Q en Z). Straatbordje met Scrabble-punten op 35th Ave & 81st St.', 2)
  on conflict (id) do update set number=excluded.number, name=excluded.name, optional=excluded.optional, location=excluded.location, era=excluded.era, layer=excluded.layer, food=excluded.food, intro=excluded.intro, reveal=excluded.reveal, background=excluded.background, sort_order=excluded.sort_order;
insert into stops (id, number, name, optional, location, era, layer, food, intro, reveal, background, sort_order) values ('s3', 3, 'De Latino-hoek - Colombia ↔ Terraza 7', false, '83-27 Roosevelt Ave + Gleane St', '1950s → nu', '2½ + 6 · Latino', 'Empanada / arepa', 'Hier begint Latijns-Amerika in Jackson Heights - niet in de jaren ''90, veel eerder. Eén gemeenschap was de voorhoede. (Terraza is overdag dicht - van buiten vertellen.)', 'Colombianen waren de eerste grote Latino-golf (jaren ''50), lang de meest zichtbare; ''Little Colombia''/Chapinero. Mede gedreven door La Violencia. Vandaag zijn Ecuadorianen de grootste groep. De schaduwkant: cocaïne-jaren ''80 op Roosevelt; journalist Manuel de Dios Unanue vermoord in 1992. Terraza 7 (Castiblanco) is het tegenbeeld: cultuur als verzet tegen gentrificatie.', 'Ketenmigratie deed het werk: elke aankomer een anker voor de volgende. ''Latino'' is geen monoliet - de buurt dwingt verschillende nationaliteiten tot nabuurschap. De verschuiving Colombiaans -> Ecuadoriaans/Dominicaans/Mexicaans is zelf een migratieverhaal.', 3)
  on conflict (id) do update set number=excluded.number, name=excluded.name, optional=excluded.optional, location=excluded.location, era=excluded.era, layer=excluded.layer, food=excluded.food, intro=excluded.intro, reveal=excluded.reveal, background=excluded.background, sort_order=excluded.sort_order;
insert into stops (id, number, name, optional, location, era, layer, food, intro, reveal, background, sort_order) values ('s4', 4, 'Roosevelt Avenue / Lorena Borjas - De Informele Stad', false, 'Roosevelt Ave, lopend westwaarts onder de 7-trein', 'nu', 'De informele stad', null, 'We lopen onder de ratelende 7-trein - de rauwe kant. Hier draait een economie die je nergens geregistreerd vindt.', 'Lorena Borjas, ''de moeder van de trans-Latinx-gemeenschap van Queens'', emigreerde in 1981 uit Mexico, was zelf slachtoffer van mensenhandel, en deed hier decennialang outreach: condooms en spuiten, hiv-tests, borgsommen, opvang in haar eigen huis. In 2017 gepardonneerd (campagne o.l.v. Danny Dromm); stierf maart 2020 als een van de eerste COVID-slachtoffers. Ze verbindt vier draden: queer, sekswerk, migratie, pandemie.', 'De informele economie onder de 7: remittances, valse documenten, zichtbaar sekswerk, bailaderos. Borjas'' verhaal is een eerlijker ingang dan een anekdote over eenzaamheid - het gaat over rechten en waardigheid.', 4)
  on conflict (id) do update set number=excluded.number, name=excluded.name, optional=excluded.optional, location=excluded.location, era=excluded.era, layer=excluded.layer, food=excluded.food, intro=excluded.intro, reveal=excluded.reveal, background=excluded.background, sort_order=excluded.sort_order;
insert into stops (id, number, name, optional, location, era, layer, food, intro, reveal, background, sort_order) values ('s5', 5, '74th Street - Little India → 9/11', false, '74th St & 37th Ave (Jackson Diner; oude Sam & Raj-hoek)', '1965 + 2001', '3 · Omslag + belonging-crisis', 'Samosa / paan', 'Bijna élke gemeenschap die we vandaag zien, voert haar aankomst terug op één wet, uit één jaar.', '1965 (Hart-Celler) schrapte de raciale quota; de eersten waren vaak hooggeschoold (Mehta kwam 1977; Sam & Raj is inmiddels dicht). De Partition van 1947 verklaart de aparte India/Pakistan/Bangladesh-gemeenschappen. En na 9/11 (2001) werd dezelfde gemeenschap verdacht gemaakt: Special Registration, detenties, surveillance, getroffen taxichauffeurs - DRUM ontstond hier om terug te vechten.', 'Tussen 1924 en 1965 blokkeerden ''national origins quotas'' Aziatische migratie bijna volledig. De tweede verdiepingen op 74th St zijn vol kantoortjes waarmee nieuwkomers het systeem navigeren (green cards, SAT-prep, notarios). De 9/11-laag is de zeef in zijn modernste vorm: van uitsluitingsclausule naar surveillancelijst.', 5)
  on conflict (id) do update set number=excluded.number, name=excluded.name, optional=excluded.optional, location=excluded.location, era=excluded.era, layer=excluded.layer, food=excluded.food, intro=excluded.intro, reveal=excluded.reveal, background=excluded.background, sort_order=excluded.sort_order;
insert into stops (id, number, name, optional, location, era, layer, food, intro, reveal, background, sort_order) values ('s6', 6, 'Diversity Plaza - De Himalaya', false, '73-19 37th Rd (Phayul op 74th St)', '1990s-nu', '5 · De Himalaya', 'Momo (blindtest)', 'Dit heet Diversity Plaza, maar kijk preciezer: dit is vooral de Himalaya - en meer dan Tibetaans.', 'Tibet, Nepal, Bhutan, Bangladesh. Veel Tibetanen zijn vluchtelingen/ballingen (na de Chinese annexatie; de Immigration Act van 1990 wees 1.000 visa toe). Het food court was bioscoop Earle -> Eagle (één letter veranderd; ''het verhaal gaat dat''). Bangladesh werd in 1971 een land na afscheiding van Pakistan.', 'Onderscheid Nepalees en Tibetaans bewust - verschillende gemeenschappen, talen, geschiedenissen. Het gebouw met vier levens (bioscoop -> porno -> Bollywood -> food court) is de palimpsest in één object. Jaarlijkse Momo Crawl.', 6)
  on conflict (id) do update set number=excluded.number, name=excluded.name, optional=excluded.optional, location=excluded.location, era=excluded.era, layer=excluded.layer, food=excluded.food, intro=excluded.intro, reveal=excluded.reveal, background=excluded.background, sort_order=excluded.sort_order;
insert into stops (id, number, name, optional, location, era, layer, food, intro, reveal, background, sort_order) values ('s7', 7, 'Arepa Lady - Renewal & de Nieuwe Uitsluiting', false, '77-17 37th Ave', 'late 80s → nu', '6 · Renewal', 'Arepa', 'We zijn in de jaren ''90 - het dieptepunt van de buurt én de eerste groene scheuten. Dit is er één.', 'María Piedad Cano begon eind jaren ''80 op een straatkar; nu een restaurant - informele economie die institutionaliseert. De schaduw is precies onze rode draad: gentrificatie is de nieuwe zeef. Niet alleen de prijs (300k -> ~1 mln), maar documentatie - kredietgeschiedenis en referenties die ook legale migranten missen. Gevolg: kelderwoningen, soms ''hot beds''.', 'Amanda Burden vergeleek gentrificatie met cholesterol (goede vs slechte soort). Maak de parallel expliciet: in 1910 een coöperatie-stemming, in 2026 een kredietscore - dezelfde machine, ander pak.', 7)
  on conflict (id) do update set number=excluded.number, name=excluded.name, optional=excluded.optional, location=excluded.location, era=excluded.era, layer=excluded.layer, food=excluded.food, intro=excluded.intro, reveal=excluded.reveal, background=excluded.background, sort_order=excluded.sort_order;
insert into stops (id, number, name, optional, location, era, layer, food, intro, reveal, background, sort_order) values ('s8', 8, 'Julio Rivera Corner - De Donkere Jaren', false, '78th St & 37th Ave', '1990', '4 · Donkere jaren', null, 'We stappen even terug, naar de donkerste jaren. Lees in stilte het straatbordje. Eén minuut.', 'In 1990 werd Julio Rivera, 29, homoseksuele barman, door skinheads vermoord. Eruit ontstond de Queens Pride Parade, opgericht door Danny Dromm - dezelfde man die later Lorena Borjas hielp pardonneren. Trek de queer lijn door: Rivera (1990) -> Borjas (2020). Mehta noemt het geen ''tolerantie'' maar ''het zakken van de wapens''.', 'Een van de eerste zaken in NY die als anti-homo hate crime werd vervolgd (eerste Queens Pride: 1993). Samenleven is hier geen harmonie maar functioneren ondanks onenigheid.', 8)
  on conflict (id) do update set number=excluded.number, name=excluded.name, optional=excluded.optional, location=excluded.location, era=excluded.era, layer=excluded.layer, food=excluded.food, intro=excluded.intro, reveal=excluded.reveal, background=excluded.background, sort_order=excluded.sort_order;
insert into stops (id, number, name, optional, location, era, layer, food, intro, reveal, background, sort_order) values ('s9', 9, 'Travers Park + 34th Ave Open Street - Het Nu', false, '76-09 34th Ave', 'nu (pandemie)', '6 · Nu', null, 'Nu komen we binnen waar we vanochtend alleen op stonden. Weten jullie nog: onthoud deze straat?', 'Jackson Heights was het epicentrum van de COVID-uitbraak in NYC - de bewoners van gedeelde kelders waren de essentiële werkers die niet konden thuiswerken (Lorena Borjas stierf in die weken). Uit de ramp groeide de 34th Avenue Open Street, die nu wordt beschreven als ''de eerste superblock van New York''. Van afgeschermde privételuin (1910) naar heroverde publieke straat (2020).', 'Elmhurst Hospital werd het nationale symbool van een overbelast systeem. Gedragen door buurtactivisten (o.a. Jim Burke). Zondag: Greenmarket bij Travers Park.', 9)
  on conflict (id) do update set number=excluded.number, name=excluded.name, optional=excluded.optional, location=excluded.location, era=excluded.era, layer=excluded.layer, food=excluded.food, intro=excluded.intro, reveal=excluded.reveal, background=excluded.background, sort_order=excluded.sort_order;
insert into stops (id, number, name, optional, location, era, layer, food, intro, reveal, background, sort_order) values ('s10', 10, 'Jahn''s - Het Slot', false, '81-04 37th Ave', 'slot', 'Slot', 'Kitchen Sink Sundae for eight', 'We eindigen waar generaties JH-families eindigden - met iets wat je onmogelijk alleen op kunt.', 'Jahn''s: de keten begon in 1897 (Bronx); déze vestiging draait sinds 1959 en is de laatste die nog bestaat (gerenoveerd 2025). De Kitchen Sink Sundae is alleen samen op te eten. Geen moraal - stel de slotvraag en laat de groep het laatste woord.', 'Tel de Tijdlijn-score; winnaar krijgt de kers.', 10)
  on conflict (id) do update set number=excluded.number, name=excluded.name, optional=excluded.optional, location=excluded.location, era=excluded.era, layer=excluded.layer, food=excluded.food, intro=excluded.intro, reveal=excluded.reveal, background=excluded.background, sort_order=excluded.sort_order;

-- 6. Tour-vragen (v2)
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s0-q1', 's0', 'open', 'Hoeveel verschillende herkomsten denk je dat er nu voor je in de rij staan?', null, null, 'Geen goed/fout - het gaat om het kijken.', 0, false, true, 0, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s1-q1', 's1', 'open', 'De buurt heet ''Heights''. Hoe hoog ligt het - en waarom heet het dan zo?', null, null, 'Het is plat (''Trains Meadow''); ''Heights'' is marketing (prestige, echo van Brooklyn Heights).', 2, true, false, 0, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s1-q2', 's1', 'mc', 'Voor wie werd deze buurt gebouwd - en wie werd geweerd?', '["Voor White Anglo-Saxon Protestants; geweerd: Joden, zwarte Amerikanen, en in de praktijk katholieken/Italianen/Grieken","Voor iedereen - er was geen selectie","Alleen voor Ieren en Italianen","Alleen voor niet-Engelssprekenden"]'::jsonb, 0, null, 2, false, false, 1, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s2-q1', 's2', 'open', 'Welk wereldberoemd bordspel werd hier bedacht - door wat voor iemand?', null, null, 'Scrabble; door een werkloze architect (Alfred Butts). Beide nodig.', 2, true, false, 0, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s2-q2', 's2', 'mc', 'Welke twee groepen waren de eersten die de exclusieve buurt binnendrongen in de jaren ''40?', '["Joodse New Yorkers en homoseksuele mannen","Colombianen en Mexicanen","Tibetanen en Nepalezen","Ieren en Italianen"]'::jsonb, 0, null, 1, false, false, 1, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s3-q1', 's3', 'mc', 'Welke Latino-gemeenschap kwam als eerste - en in welk decennium?', '["Colombianen, jaren ''50 (vóór de Aziaten)","Mexicanen, jaren ''90","Dominicanen, jaren ''70","Ecuadorianen, jaren ''80"]'::jsonb, 0, null, 2, true, false, 0, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s3-q2', 's3', 'mc', 'Welke gemeenschap is vandaag de gróótste in Jackson Heights?', '["Ecuadorianen","Colombianen","Indiërs","Tibetanen"]'::jsonb, 0, null, 1, false, false, 1, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s3-q3', 's3', 'mc', 'Proef de arepa - van welk graan is hij gemaakt?', '["Maïs","Tarwe","Rijst","Gerst"]'::jsonb, 0, null, 1, false, false, 2, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s3-q4', 's3', 'open', 'Terraza 7 / Freddy Castiblanco noemt zijn zaak ''verzet''. Verzet tegen wat?', null, null, 'Tegen gentrificatie / verdringing van de gemeenschap.', 2, false, false, 3, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s4-q1', 's4', 'mc', 'Migranten sturen vanaf straten als deze geld naar huis (''remittances''). Hoeveel gaat er wereldwijd jaarlijks naar lage- en middeninkomenslanden?', '["~6 miljard dollar","~65 miljard dollar","~650 miljard dollar","~6 biljoen dollar"]'::jsonb, 2, null, 1, false, false, 0, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s4-q2', 's4', 'open', 'Lorena Borjas werd ''de moeder van de trans-Latinx-gemeenschap van Queens'' genoemd. Wat deed ze hier op Roosevelt?', null, null, 'Outreach voor transvrouwen/sekswerkers/ongedocumenteerden: condooms en spuiten uitdelen, hiv-tests, borgsommen, opvang. Punt bij elke zinnige kern.', 2, false, false, 1, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s5-q1', 's5', 'open', 'Eén wet uit één jaar verklaart bijna alle migratie hier. Welk jaar - en wat deed die wet?', null, null, '1965, Immigration & Nationality Act (Hart-Celler): schrapte de raciale quota en opende migratie uit Azië. Jaartal + strekking.', 2, true, false, 0, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s5-q2', 's5', 'open', 'Kijk omhoog: wat doen al die kantoortjes op de tweede verdiepingen?', null, null, 'Diensten waarmee nieuwkomers het systeem navigeren: green cards, rijbewijzen, belasting, SAT-prep, scheidingen, begrafenissen. Punt bij elke kern.', 1, false, false, 1, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s5-q3', 's5', 'mc', 'Na welke gebeurtenis werden Zuid-Aziatische en moslimmannen hier doelwit van ''Special Registration'', detenties en surveillance?', '["Na 9/11 (2001)","Tijdens de Golfoorlog (1991)","Na de val van de Berlijnse Muur (1989)","Tijdens COVID (2020)"]'::jsonb, 0, null, 2, true, false, 2, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s5-q4', 's5', 'mc', 'Welke gebeurtenis splitste India en Pakistan in 1947 tot aparte landen?', '["De Partition (deling van Brits-Indië)","De Tweede Wereldoorlog","De stichting van de VN","Een staatsgreep"]'::jsonb, 0, null, 1, false, false, 3, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s6-q1', 's6', 'mc', 'Veel mensen zeggen ''Tibetaans'', maar welke gemeenschap is hier minstens zo groot?', '["De Nepalese","De Japanse","De Koreaanse","De Vietnamese"]'::jsonb, 0, null, 1, false, false, 0, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s6-q2', 's6', 'mc', 'Veel Tibetanen hier zijn geen ''gewone'' migranten. Wat dan wel?', '["Vluchtelingen / ballingen (na de Chinese annexatie van Tibet)","Uitwisselingsstudenten","Seizoensarbeiders","Toeristen die bleven"]'::jsonb, 0, null, 1, false, false, 1, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s6-q3', 's6', 'open', 'Dit was de bioscoop ''The Earle'', daarna ''The Eagle''. Wat veranderden de eigenaren - en waarom maar dát?', null, null, 'Eén letter (Earle -> Eagle), om kosten te sparen. (Anekdote - ''het verhaal gaat dat''.)', 2, true, false, 2, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s7-q1', 's7', 'mc', 'Hoe verkocht de Arepa Lady (María Piedad Cano) haar arepa''s oorspronkelijk?', '["Vanaf een straatkar","In een chic restaurant","Online","Op de Greenmarket"]'::jsonb, 0, null, 1, false, false, 0, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s7-q2', 's7', 'open', 'In 1910 hield een coöperatie-zeef mensen buiten. Wat is vandaag de nieuwe ''zeef'' die nieuwkomers buiten luxe-appartementen houdt?', null, null, 'Documentatie (kredietgeschiedenis, referenties, papieren) plus de prijs. Punt bij ''documenten/kredietcheck''.', 2, false, false, 1, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s8-q1', 's8', 'open', 'Naar wie is deze hoek vernoemd - en welke jaarlijkse gebeurtenis komt rechtstreeks voort uit zijn dood in 1990?', null, null, 'Julio Rivera; de Queens Pride Parade (opgericht door Danny Dromm). Naam + gebeurtenis.', 2, true, false, 0, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s9-q1', 's9', 'mc', 'Tijdens welke wereldgebeurtenis werd deze autovrije straat een ''superblock''? (cliffhanger van Stop 1)', '["De COVID-pandemie (2020)","9/11","De financiële crisis van 2008","Orkaan Sandy (2012)"]'::jsonb, 0, null, 2, true, false, 0, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;
insert into questions (id, group_id, type, prompt, options, correct_index, model_answer, points, is_timeline, discussion, sort_order, active) values ('s10-q1', 's10', 'open', 'Slotvraag (discussie, niet gescoord): Je hebt de wereld doorkruist zonder te vliegen. Van wie is deze buurt nu - en wie bepaalt dat morgen?', null, null, 'Geen goed/fout - discussie. Niet scoren.', 0, false, true, 0, true)
  on conflict (id) do update set group_id=excluded.group_id, type=excluded.type, prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, model_answer=excluded.model_answer, points=excluded.points, is_timeline=excluded.is_timeline, discussion=excluded.discussion, sort_order=excluded.sort_order, active=true;

-- 7. Activiteiten (v2)
insert into activities (id, stop_id, title, body, sort_order) values ('s6-act-momo', 's6', 'Momo-blindtest', 'Proef momo''s van twee/drie plekken; raad Tibetaans vs Nepalees. De host beoordeelt.', 0) on conflict (id) do update set stop_id=excluded.stop_id, title=excluded.title, body=excluded.body, sort_order=excluded.sort_order;
insert into activities (id, stop_id, title, body, sort_order) values ('s8-act-stilte', 's8', 'Stilteminuut', 'Eén minuut stilte; lees het bordje. Geen pathos.', 0) on conflict (id) do update set stop_id=excluded.stop_id, title=excluded.title, body=excluded.body, sort_order=excluded.sort_order;
insert into activities (id, stop_id, title, body, sort_order) values ('s10-act-tally', 's10', 'Eindstand & de kers', 'Tel de Tijdlijn-score. De winnaar krijgt de kers van de sundae.', 0) on conflict (id) do update set stop_id=excluded.stop_id, title=excluded.title, body=excluded.body, sort_order=excluded.sort_order;
