-- =============================================================================
-- The Arrivals - 0008: restaurants (live eten- & taalkaart).
-- Publiek leesbaar; bewerken via /admin (admin_secret). Draai in de Supabase
-- SQL Editor. Idempotent.
-- =============================================================================

create table if not exists restaurants (
  id text primary key,
  name text not null,
  community_id text not null,        -- verwijst naar COMMUNITIES (code)
  cuisine text,
  price text,
  address text,
  x numeric not null default 50,     -- kaartpositie 0-100
  y numeric not null default 50,
  lang_group text,                   -- verwijst naar PHRASE_GROUPS (code)
  tour int,
  rating numeric,
  rating_count int,
  rating_source text,
  consensus text,
  dish text,
  dish_source text,
  quotes jsonb not null default '[]'::jsonb,
  sort_order int not null default 0,
  active boolean not null default true
);

alter table restaurants enable row level security;
drop policy if exists "read restaurants" on restaurants;
create policy "read restaurants" on restaurants for select using (true);
grant select on restaurants to anon, authenticated;

create or replace function admin_upsert_restaurant(p_secret text, p_row jsonb)
returns void language plpgsql security definer set search_path = public as $$
begin
  perform assert_admin(p_secret);
  insert into restaurants (id, name, community_id, cuisine, price, address, x, y, lang_group,
    tour, rating, rating_count, rating_source, consensus, dish, dish_source, quotes, sort_order, active)
  values (
    coalesce(nullif(p_row->>'id',''),'r-'||substr(replace(gen_random_uuid()::text,'-',''),1,8)),
    p_row->>'name', p_row->>'community_id', p_row->>'cuisine', p_row->>'price', p_row->>'address',
    coalesce(nullif(p_row->>'x','')::numeric, 50), coalesce(nullif(p_row->>'y','')::numeric, 50),
    p_row->>'lang_group', nullif(p_row->>'tour','')::int,
    nullif(p_row->>'rating','')::numeric, nullif(p_row->>'rating_count','')::int, p_row->>'rating_source',
    p_row->>'consensus', p_row->>'dish', p_row->>'dish_source',
    coalesce(p_row->'quotes','[]'::jsonb),
    coalesce(nullif(p_row->>'sort_order','')::int, 0),
    coalesce((p_row->>'active')::boolean, true))
  on conflict (id) do update set
    name=excluded.name, community_id=excluded.community_id, cuisine=excluded.cuisine,
    price=excluded.price, address=excluded.address, x=excluded.x, y=excluded.y,
    lang_group=excluded.lang_group, tour=excluded.tour, rating=excluded.rating,
    rating_count=excluded.rating_count, rating_source=excluded.rating_source,
    consensus=excluded.consensus, dish=excluded.dish, dish_source=excluded.dish_source,
    quotes=excluded.quotes, sort_order=excluded.sort_order, active=excluded.active;
end;
$$;

create or replace function admin_delete_restaurant(p_secret text, p_id text)
returns void language plpgsql security definer set search_path = public as $$
begin perform assert_admin(p_secret); delete from restaurants where id = p_id; end;
$$;

grant execute on function
  admin_upsert_restaurant(text, jsonb), admin_delete_restaurant(text, text)
to anon, authenticated;

-- Seed: de 18 startrestaurants
insert into restaurants (id, name, community_id, cuisine, price, address, x, y, lang_group, tour, rating, rating_count, rating_source, consensus, dish, dish_source, quotes, sort_order, active) values ('rajbhog', 'Rajbhog Sweets', 'south_asian', 'Gujarati · Veg', '$', '72-27 37th Ave', 25, 50, 'hindi', 1, 4.2, 300, 'Google', 'Zuid-Gujarati snacks, dampende dhokla en een betaalbare thali op de 37th Avenue-strip.', 'Gujarati thali', 'Vaste klanten', '[{"text":"Verse dhokla en een thali die de tafel vult.","source":"Google-reviewer"},{"text":"Betrouwbare snoepbalie als de festivals eraan komen.","source":"Buurtbewoner"}]'::jsonb, 1, true)
  on conflict (id) do update set name=excluded.name, community_id=excluded.community_id, cuisine=excluded.cuisine, price=excluded.price, address=excluded.address, x=excluded.x, y=excluded.y, lang_group=excluded.lang_group, tour=excluded.tour, rating=excluded.rating, rating_count=excluded.rating_count, rating_source=excluded.rating_source, consensus=excluded.consensus, dish=excluded.dish, dish_source=excluded.dish_source, quotes=excluded.quotes, sort_order=excluded.sort_order, active=excluded.active;
insert into restaurants (id, name, community_id, cuisine, price, address, x, y, lang_group, tour, rating, rating_count, rating_source, consensus, dish, dish_source, quotes, sort_order, active) values ('samudra', 'Samudra', 'south_asian', 'Zuid-Indiaas · Veg', '$', '75-18 37th Ave', 34, 52, 'hindi', 2, 4.1, 235, 'Restaurantji', 'Een rustig vegetarisch pareltje - knapperige dosas en paneer uthappam, met zachte Bollywood-oldies.', 'Paper dosa', 'Restaurantji', '[{"text":"Knapperig, lekker, vers gemaakt.","source":"Restaurantji"},{"text":"Het is essentieel om een dosa te bestellen.","source":"Untapped New York"}]'::jsonb, 2, true)
  on conflict (id) do update set name=excluded.name, community_id=excluded.community_id, cuisine=excluded.cuisine, price=excluded.price, address=excluded.address, x=excluded.x, y=excluded.y, lang_group=excluded.lang_group, tour=excluded.tour, rating=excluded.rating, rating_count=excluded.rating_count, rating_source=excluded.rating_source, consensus=excluded.consensus, dish=excluded.dish, dish_source=excluded.dish_source, quotes=excluded.quotes, sort_order=excluded.sort_order, active=excluded.active;
insert into restaurants (id, name, community_id, cuisine, price, address, x, y, lang_group, tour, rating, rating_count, rating_source, consensus, dish, dish_source, quotes, sort_order, active) values ('jackson_diner', 'Jackson Diner', 'south_asian', 'Noord-Indiaas', '$$', '37-47 74th St', 30, 55, 'hindi', 3, 4, 724, 'Yelp', 'Een Little India-instituut sinds 1980 - groot, groepsvriendelijk, geliefd om gulle biryani en butter chicken.', 'Chicken biryani', 'The Infatuation', '[{"text":"Topkwaliteit, en grotere porties dan de rest van de buurt.","source":"Yelp-reviewer"},{"text":"Ideaal om biryani te delen met een grote groep.","source":"The Infatuation"}]'::jsonb, 3, true)
  on conflict (id) do update set name=excluded.name, community_id=excluded.community_id, cuisine=excluded.cuisine, price=excluded.price, address=excluded.address, x=excluded.x, y=excluded.y, lang_group=excluded.lang_group, tour=excluded.tour, rating=excluded.rating, rating_count=excluded.rating_count, rating_source=excluded.rating_source, consensus=excluded.consensus, dish=excluded.dish, dish_source=excluded.dish_source, quotes=excluded.quotes, sort_order=excluded.sort_order, active=excluded.active;
insert into restaurants (id, name, community_id, cuisine, price, address, x, y, lang_group, tour, rating, rating_count, rating_source, consensus, dish, dish_source, quotes, sort_order, active) values ('maharaja', 'Maharaja Sweets & Snacks', 'south_asian', 'Zoet · Chaat', '$', '73-10 37th Rd', 27, 63, 'hindi', 4, 4.3, 410, 'Google', 'Vitrines vol mithai vooraan, een bruisende chaat-balie achterin - de zoet-en-pittig-stop bij Diversity Plaza.', 'Samosa chaat', 'Untapped New York', '[{"text":"Gulab jamun waar je meer van wilt.","source":"Untapped New York"},{"text":"Betaalbare snacks en zoetigheid, altijd vol.","source":"Google-reviewer"}]'::jsonb, 4, true)
  on conflict (id) do update set name=excluded.name, community_id=excluded.community_id, cuisine=excluded.cuisine, price=excluded.price, address=excluded.address, x=excluded.x, y=excluded.y, lang_group=excluded.lang_group, tour=excluded.tour, rating=excluded.rating, rating_count=excluded.rating_count, rating_source=excluded.rating_source, consensus=excluded.consensus, dish=excluded.dish, dish_source=excluded.dish_source, quotes=excluded.quotes, sort_order=excluded.sort_order, active=excluded.active;
insert into restaurants (id, name, community_id, cuisine, price, address, x, y, lang_group, tour, rating, rating_count, rating_source, consensus, dish, dish_source, quotes, sort_order, active) values ('mustang', 'Mustang Thakali Kitchen', 'himalayan', 'Nepalees', '$$', '74-14 37th Rd', 30, 66, 'nepali', 5, 4.4, 180, 'Google', 'Thakali-sets uit de bergvalleien van Nepal - zwarte bonen, gefermenteerde gundruk en rijst in ghee.', 'Thakali thali', 'Vaste klanten', '[{"text":"De meest authentieke Thakali-set in de buurt.","source":"Google-reviewer"},{"text":"Gul, huiselijk en betaalbaar.","source":"Buurtbewoner"}]'::jsonb, 5, true)
  on conflict (id) do update set name=excluded.name, community_id=excluded.community_id, cuisine=excluded.cuisine, price=excluded.price, address=excluded.address, x=excluded.x, y=excluded.y, lang_group=excluded.lang_group, tour=excluded.tour, rating=excluded.rating, rating_count=excluded.rating_count, rating_source=excluded.rating_source, consensus=excluded.consensus, dish=excluded.dish, dish_source=excluded.dish_source, quotes=excluded.quotes, sort_order=excluded.sort_order, active=excluded.active;
insert into restaurants (id, name, community_id, cuisine, price, address, x, y, lang_group, tour, rating, rating_count, rating_source, consensus, dish, dish_source, quotes, sort_order, active) values ('lhasa', 'Lhasa Fast Food', 'himalayan', 'Tibetaans', '$', '37-50 74th St', 31, 60, 'tibetan', 6, 4.6, 89, 'Tripadvisor', 'Een piepklein zaaltje met vijf tafels achter een telefoonwinkel - stilletjes de beste momos van de buurt.', 'Momos met rund & bieslook', 'The Infatuation', '[{"text":"Een van de beste dumplings van de hele buurt.","source":"The Infatuation"},{"text":"Sappig, mals, ontzettend smaakvol.","source":"Tripadvisor-reviewer"}]'::jsonb, 6, true)
  on conflict (id) do update set name=excluded.name, community_id=excluded.community_id, cuisine=excluded.cuisine, price=excluded.price, address=excluded.address, x=excluded.x, y=excluded.y, lang_group=excluded.lang_group, tour=excluded.tour, rating=excluded.rating, rating_count=excluded.rating_count, rating_source=excluded.rating_source, consensus=excluded.consensus, dish=excluded.dish, dish_source=excluded.dish_source, quotes=excluded.quotes, sort_order=excluded.sort_order, active=excluded.active;
insert into restaurants (id, name, community_id, cuisine, price, address, x, y, lang_group, tour, rating, rating_count, rating_source, consensus, dish, dish_source, quotes, sort_order, active) values ('phayul', 'Phayul', 'himalayan', 'Tibetaans', '$$', '37-65 74th St', 34, 61, 'tibetan', 7, 4.5, 260, 'Tripadvisor', 'Een verborgen trap op: een langer menu met vurige Tibetaanse roerbakgerechten dat sommigen boven Lhasa zetten.', 'Beef shapta', 'The Infatuation', '[{"text":"Zo goed als we Lhasa vinden, dit is nog beter.","source":"The Infatuation"},{"text":"Authentieke smaken in een verborgen pareltje.","source":"Tripadvisor-reviewer"}]'::jsonb, 7, true)
  on conflict (id) do update set name=excluded.name, community_id=excluded.community_id, cuisine=excluded.cuisine, price=excluded.price, address=excluded.address, x=excluded.x, y=excluded.y, lang_group=excluded.lang_group, tour=excluded.tour, rating=excluded.rating, rating_count=excluded.rating_count, rating_source=excluded.rating_source, consensus=excluded.consensus, dish=excluded.dish, dish_source=excluded.dish_source, quotes=excluded.quotes, sort_order=excluded.sort_order, active=excluded.active;
insert into restaurants (id, name, community_id, cuisine, price, address, x, y, lang_group, tour, rating, rating_count, rating_source, consensus, dish, dish_source, quotes, sort_order, active) values ('himalayan_yak', 'Himalayan Yak', 'himalayan', 'Nepalees · Tibetaans', '$$', '72-20 Roosevelt Ave', 24, 75, 'nepali', 8, 4.3, 520, 'Google', 'Een ruime eetzaal met houtsnijwerk voor complete Nepalese thali-sets, yak-bottensoep en momos bij het dozijn.', 'Nepalese thali-set', 'Gothamist', '[{"text":"Echt goed Nepalees eten - de momos zijn het wachten waard.","source":"Yelp-reviewer"},{"text":"Zit-restaurant voor thali en botertee.","source":"Google-reviewer"}]'::jsonb, 8, true)
  on conflict (id) do update set name=excluded.name, community_id=excluded.community_id, cuisine=excluded.cuisine, price=excluded.price, address=excluded.address, x=excluded.x, y=excluded.y, lang_group=excluded.lang_group, tour=excluded.tour, rating=excluded.rating, rating_count=excluded.rating_count, rating_source=excluded.rating_source, consensus=excluded.consensus, dish=excluded.dish, dish_source=excluded.dish_source, quotes=excluded.quotes, sort_order=excluded.sort_order, active=excluded.active;
insert into restaurants (id, name, community_id, cuisine, price, address, x, y, lang_group, tour, rating, rating_count, rating_source, consensus, dish, dish_source, quotes, sort_order, active) values ('music_box', 'Music Box', 'lgbtq', 'Nachtleven', '$$', '40-08 74th St', 34, 71, 'spanish', 9, 4.2, 120, 'Google', 'Een lang draaiende queer Latin-clubavond waar cumbia de ballroom-vloer ontmoet, net naast 74th Street.', 'Cumbia & vogue-avond', 'Buurtverhaal', '[{"text":"Zweterig, vrolijk en onmiskenbaar Queens.","source":"Vaste gast"},{"text":"Latin-nachtleven met een vogue-twist.","source":"Buurtverhaal"}]'::jsonb, 9, true)
  on conflict (id) do update set name=excluded.name, community_id=excluded.community_id, cuisine=excluded.cuisine, price=excluded.price, address=excluded.address, x=excluded.x, y=excluded.y, lang_group=excluded.lang_group, tour=excluded.tour, rating=excluded.rating, rating_count=excluded.rating_count, rating_source=excluded.rating_source, consensus=excluded.consensus, dish=excluded.dish, dish_source=excluded.dish_source, quotes=excluded.quotes, sort_order=excluded.sort_order, active=excluded.active;
insert into restaurants (id, name, community_id, cuisine, price, address, x, y, lang_group, tour, rating, rating_count, rating_source, consensus, dish, dish_source, quotes, sort_order, active) values ('coatzingo', 'Taqueria Coatzingo', 'mexican', 'Mexicaans', '$', '76-05 Roosevelt Ave', 39, 81, 'spanish', 10, 4.2, 1600, 'Google', 'De oudste en grootste van de Mexicaanse keukens in de buurt - door en door Puebla, met geitenbarbacoa in het weekend.', 'Geitenbarbacoa (weekend)', 'Gothamist', '[{"text":"De oudste en grootste Mexicaan van Jackson Heights.","source":"Gothamist"},{"text":"Door en door Puebla - chicharrón in salsa verde.","source":"Gothamist"}]'::jsonb, 10, true)
  on conflict (id) do update set name=excluded.name, community_id=excluded.community_id, cuisine=excluded.cuisine, price=excluded.price, address=excluded.address, x=excluded.x, y=excluded.y, lang_group=excluded.lang_group, tour=excluded.tour, rating=excluded.rating, rating_count=excluded.rating_count, rating_source=excluded.rating_source, consensus=excluded.consensus, dish=excluded.dish, dish_source=excluded.dish_source, quotes=excluded.quotes, sort_order=excluded.sort_order, active=excluded.active;
insert into restaurants (id, name, community_id, cuisine, price, address, x, y, lang_group, tour, rating, rating_count, rating_source, consensus, dish, dish_source, quotes, sort_order, active) values ('arepa_lady', 'Arepa Lady', 'colombian', 'Colombiaans', '$', '77-02 Roosevelt Ave', 42, 76, 'spanish', 11, 4.3, 321, 'Restaurantji', 'María Cano’s legendarische Roosevelt Ave-bakplaat, nu een winkelpui - zoete maïsarepas onder een deken van kaas.', 'Arepa de choclo', 'Restaurantji', '[{"text":"Behield de authentieke Zuid-Amerikaanse straatstijl.","source":"Yelp-reviewer"},{"text":"Wat een geweldige maaltijd - we komen terug.","source":"Restaurantji"}]'::jsonb, 11, true)
  on conflict (id) do update set name=excluded.name, community_id=excluded.community_id, cuisine=excluded.cuisine, price=excluded.price, address=excluded.address, x=excluded.x, y=excluded.y, lang_group=excluded.lang_group, tour=excluded.tour, rating=excluded.rating, rating_count=excluded.rating_count, rating_source=excluded.rating_source, consensus=excluded.consensus, dish=excluded.dish, dish_source=excluded.dish_source, quotes=excluded.quotes, sort_order=excluded.sort_order, active=excluded.active;
insert into restaurants (id, name, community_id, cuisine, price, address, x, y, lang_group, tour, rating, rating_count, rating_source, consensus, dish, dish_source, quotes, sort_order, active) values ('friends', 'Friends Tavern', 'lgbtq', 'Bar · Latin', '$$', '78-11 Roosevelt Ave', 49, 85, 'spanish', 12, 4.4, 300, 'Google', 'Open sinds 1978 - de langstlopende gay Latino-bar van Queens en hoeksteen van de eerste migrant-geleide Pride.', 'Een koud biertje & decennia geschiedenis', 'Buurtverhaal', '[{"text":"Een instituut van het Latijns LGBTQ+-nachtleven in Queens.","source":"Buurtverhaal"},{"text":"Iedereen welkom - de geschiedenis leeft op deze muren.","source":"Vaste gast"}]'::jsonb, 12, true)
  on conflict (id) do update set name=excluded.name, community_id=excluded.community_id, cuisine=excluded.cuisine, price=excluded.price, address=excluded.address, x=excluded.x, y=excluded.y, lang_group=excluded.lang_group, tour=excluded.tour, rating=excluded.rating, rating_count=excluded.rating_count, rating_source=excluded.rating_source, consensus=excluded.consensus, dish=excluded.dish, dish_source=excluded.dish_source, quotes=excluded.quotes, sort_order=excluded.sort_order, active=excluded.active;
insert into restaurants (id, name, community_id, cuisine, price, address, x, y, lang_group, tour, rating, rating_count, rating_source, consensus, dish, dish_source, quotes, sort_order, active) values ('birria', 'Birria-Landia', 'mexican', 'Mexicaans', '$', '78-14 Roosevelt Ave', 46, 81, 'spanish', 13, 4.6, 1500, 'Google', 'De Tijuana-style truck die NYC voor birria liet vallen - in bouillon gedoopte taco’s en een bakje rijke consomé.', 'Birria taco’s + consomé', 'The Infatuation', '[{"text":"Maakt de beste birria van de stad, punt.","source":"The Infatuation"},{"text":"Limoen, mals vlees, adobo, druipend vet - alles smelt samen.","source":"The Infatuation"}]'::jsonb, 13, true)
  on conflict (id) do update set name=excluded.name, community_id=excluded.community_id, cuisine=excluded.cuisine, price=excluded.price, address=excluded.address, x=excluded.x, y=excluded.y, lang_group=excluded.lang_group, tour=excluded.tour, rating=excluded.rating, rating_count=excluded.rating_count, rating_source=excluded.rating_source, consensus=excluded.consensus, dish=excluded.dish, dish_source=excluded.dish_source, quotes=excluded.quotes, sort_order=excluded.sort_order, active=excluded.active;
insert into restaurants (id, name, community_id, cuisine, price, address, x, y, lang_group, tour, rating, rating_count, rating_source, consensus, dish, dish_source, quotes, sort_order, active) values ('pollos_mario', 'Pollos a la Brasa Mario', 'colombian', 'Colombiaans', '$', '81-01 Roosevelt Ave', 54, 75, 'spanish', 14, 4.4, 900, 'Google', 'Op houtskool geblakerde rotisserie-kip met ají - de geur trekt je zo van de 7-trein.', 'Rotisserie-kip', 'Vaste klanten', '[{"text":"Krokante chicharrón en kip vol smaak.","source":"Yelp-reviewer"},{"text":"Beste houtskoolkip op Roosevelt.","source":"Google-reviewer"}]'::jsonb, 14, true)
  on conflict (id) do update set name=excluded.name, community_id=excluded.community_id, cuisine=excluded.cuisine, price=excluded.price, address=excluded.address, x=excluded.x, y=excluded.y, lang_group=excluded.lang_group, tour=excluded.tour, rating=excluded.rating, rating_count=excluded.rating_count, rating_source=excluded.rating_source, consensus=excluded.consensus, dish=excluded.dish, dish_source=excluded.dish_source, quotes=excluded.quotes, sort_order=excluded.sort_order, active=excluded.active;
insert into restaurants (id, name, community_id, cuisine, price, address, x, y, lang_group, tour, rating, rating_count, rating_source, consensus, dish, dish_source, quotes, sort_order, active) values ('pequena', 'La Pequeña Colombia', 'colombian', 'Colombiaans', '$$', '83-27 Roosevelt Ave', 61, 77, 'spanish', 15, 4.2, 1100, 'Google', 'De volledige paisa-schotel onder één dak - de zit-klassieker die Little Colombia zijn naam gaf.', 'Bandeja paisa', 'Tripadvisor', '[{"text":"Waar voor je geld - stevig en authentiek.","source":"Tripadvisor-reviewer"},{"text":"Ik kan La Pequeña absoluut aanraden.","source":"Tripadvisor-reviewer"}]'::jsonb, 15, true)
  on conflict (id) do update set name=excluded.name, community_id=excluded.community_id, cuisine=excluded.cuisine, price=excluded.price, address=excluded.address, x=excluded.x, y=excluded.y, lang_group=excluded.lang_group, tour=excluded.tour, rating=excluded.rating, rating_count=excluded.rating_count, rating_source=excluded.rating_source, consensus=excluded.consensus, dish=excluded.dish, dish_source=excluded.dish_source, quotes=excluded.quotes, sort_order=excluded.sort_order, active=excluded.active;
insert into restaurants (id, name, community_id, cuisine, price, address, x, y, lang_group, tour, rating, rating_count, rating_source, consensus, dish, dish_source, quotes, sort_order, active) values ('hornado', 'Hornado Ecuatoriano', 'ecuadorian', 'Ecuadoriaans', '$', '85-10 Roosevelt Ave', 66, 81, 'spanish', 16, 4.3, 220, 'Google', 'Quito-style zondagse varkensbraad, ter plekke geplukt met krokante llapingachos en geroosterde mote.', 'Hornado (varkensbraad)', 'Vaste klanten', '[{"text":"Varkensbraad net als thuis in de sierra.","source":"Google-reviewer"},{"text":"Stevige borden en vriendelijk personeel.","source":"Buurtbewoner"}]'::jsonb, 16, true)
  on conflict (id) do update set name=excluded.name, community_id=excluded.community_id, cuisine=excluded.cuisine, price=excluded.price, address=excluded.address, x=excluded.x, y=excluded.y, lang_group=excluded.lang_group, tour=excluded.tour, rating=excluded.rating, rating_count=excluded.rating_count, rating_source=excluded.rating_source, consensus=excluded.consensus, dish=excluded.dish, dish_source=excluded.dish_source, quotes=excluded.quotes, sort_order=excluded.sort_order, active=excluded.active;
insert into restaurants (id, name, community_id, cuisine, price, address, x, y, lang_group, tour, rating, rating_count, rating_source, consensus, dish, dish_source, quotes, sort_order, active) values ('manabita', 'El Sabor Manabita', 'ecuadorian', 'Ecuadoriaans', '$', '88-15 Roosevelt Ave', 71, 82, 'spanish', 17, 4.2, 140, 'Google', 'Kustkeuken uit Manabí - heldere encebollado-vissoep, groene-bananen-bolón en verse ceviche.', 'Encebollado', 'Tripadvisor', '[{"text":"Mijn broer nam de encebollado en genoot er echt van.","source":"Tripadvisor-reviewer"},{"text":"Vers, kustachtig en vol smaak.","source":"Google-reviewer"}]'::jsonb, 17, true)
  on conflict (id) do update set name=excluded.name, community_id=excluded.community_id, cuisine=excluded.cuisine, price=excluded.price, address=excluded.address, x=excluded.x, y=excluded.y, lang_group=excluded.lang_group, tour=excluded.tour, rating=excluded.rating, rating_count=excluded.rating_count, rating_source=excluded.rating_source, consensus=excluded.consensus, dish=excluded.dish, dish_source=excluded.dish_source, quotes=excluded.quotes, sort_order=excluded.sort_order, active=excluded.active;
insert into restaurants (id, name, community_id, cuisine, price, address, x, y, lang_group, tour, rating, rating_count, rating_source, consensus, dish, dish_source, quotes, sort_order, active) values ('evolution', 'Club Evolution', 'lgbtq', 'Nachtleven', '$$', '76-19 Roosevelt Ave', 44, 85, 'spanish', 18, 4.1, 160, 'Google', 'Late dragshows en reggaetón op de Roosevelt Ave-strip - pailletten onder de verhoogde sporen.', 'Dragshow in het weekend', 'Buurtverhaal', '[{"text":"De dragshows zijn een hele productie.","source":"Vaste gast"},{"text":"Reggaetón tot laat onder de 7-lijn.","source":"Buurtverhaal"}]'::jsonb, 18, true)
  on conflict (id) do update set name=excluded.name, community_id=excluded.community_id, cuisine=excluded.cuisine, price=excluded.price, address=excluded.address, x=excluded.x, y=excluded.y, lang_group=excluded.lang_group, tour=excluded.tour, rating=excluded.rating, rating_count=excluded.rating_count, rating_source=excluded.rating_source, consensus=excluded.consensus, dish=excluded.dish, dish_source=excluded.dish_source, quotes=excluded.quotes, sort_order=excluded.sort_order, active=excluded.active;
